[BI-380] Update sidebar layout to stay in place and be independently scrollable from page scroll
Breeding-Insight/bi-web pull request #111
Opened 2021-08-23 20:51 UTC by nickpalladino

2021-09-02 21:52 UTC, HMS17 approved these changes

2021-09-03 19:22 UTC, timparsons requested changes
A couple of small things.  Everything else looks great!

2021-09-03 19:22 UTC, timparsons commented on src/components/layouts/BaseSideBarLayout.vue
> +import Footer from "@/components/layouts/Footer.vue";
I don't think this is used in the component

2021-09-03 19:22 UTC, timparsons commented on src/assets/scss/main.scss
> +.main-footer {
I'm wondering if it'd be better to modify the structure of the HTML to have the main footer be a part of the main body, rather than modifying the footer to look like it's a part of the main body via CSS.

2021-09-03 19:22 UTC, timparsons commented on src/assets/scss/main.scss
>  #versionInfo {
Could some margin padding be added to the top of the version info in the menu footer?  It feels a little cramped with the menu items

2021-09-07 15:03 UTC, nickpalladino commented on src/components/layouts/BaseSideBarLayout.vue
> +import Footer from "@/components/layouts/Footer.vue";
ah ya thanks that was from some early messing around that was left over. Removed and pushed changes.

2021-09-07 15:06 UTC, nickpalladino commented on src/assets/scss/main.scss
> +.main-footer {
ya that was the first approach I tried but had some display issues and got tired of messing with it so switched to keeping the footer and modifying it based on the layout. Germinate does a similar thing as well, has a footer and uses margin to move it around. I guess I'd rather keep it then spend time messing around trying to get it to work the other way. I'm not opposed to reconsidering in the future though.

2021-09-07 15:34 UTC, nickpalladino commented on src/assets/scss/main.scss
>  #versionInfo {
Added some padding and pushed changes. I'll create another card as well to make the version fixed to the bottom rather than scroll.

2021-09-07 17:36 UTC, timparsons approved these changes

2021-09-07 20:22 UTC, merged