[BI-1047] - Convert expandable datatables to Buefy
Breeding-Insight/bi-web pull request #112
Opened 2021-08-25 19:39 UTC by HMS17

Following [BI-895](https://github.com/Breeding-Insight/taf/pull/9/), converting other expandable datatables to use Buefy ExpandableTable component.

Converted following tables to use ExpandableTable
- Admin Users Table
- Admin Programs Table
- Program Locations Table
- Trials Table
- Observations List Table
 
Removed ExpandableRowTable.vue and associate unit tests
Modified Program Users Table to use the heading "Role" instead of "Roles"

Linked to PR [taf/BI-1047](https://github.com/Breeding-Insight/taf/pull/17)

2021-08-30 20:54 UTC, nickpalladino commented on src/components/admin/AdminProgramsTable.vue
> +    ChevronRightIcon, ChevronDownIcon
Think some of these icon imports could be cleaned up, don't seem to be needed here.

2021-08-30 20:54 UTC, nickpalladino commented on src/components/admin/AdminProgramsTable.vue
> +    <div class="is-clearfix"></div>
I noticed this being used in a bunch of the table pages but not for trials or observations. Not sure what it's used for?

2021-08-31 14:51 UTC, HMS17 commented on src/components/admin/AdminProgramsTable.vue
> +    <div class="is-clearfix"></div>
I'm not quite sure. I'm aware clearfix can be used to help fix broken layouts and I was patterning my changes off the PR for converting the Program Users table, which also included adding this.

2021-08-31 14:52 UTC, HMS17 commented on src/components/admin/AdminProgramsTable.vue
> +    ChevronRightIcon, ChevronDownIcon
Which icons are you speaking of? Since I do think the Chevron icons are used (when sorting columns).

2021-08-31 15:10 UTC, nickpalladino commented on src/components/admin/AdminProgramsTable.vue
> +    ChevronRightIcon, ChevronDownIcon
ya chevron, I think those should be in the buefy icon pack so doesn't seem like they'd be needed in this component

2021-08-31 15:12 UTC, nickpalladino commented on src/components/admin/AdminProgramsTable.vue
> +    <div class="is-clearfix"></div>
ok, I guess if it's serving some purpose it should probably be in all of the tables.

2021-08-31 20:01 UTC, HMS17 commented on src/components/admin/AdminProgramsTable.vue
> +    ChevronRightIcon, ChevronDownIcon
That was another change where I was mirroring the Program Users table conversion.

2021-08-31 20:25 UTC, nickpalladino commented on src/components/admin/AdminProgramsTable.vue
> +    ChevronRightIcon, ChevronDownIcon
ya, just wondering if that slipped through when that first one was reviewed. It's not a big deal, I'll approve either way.

2021-09-02 14:14 UTC, nickpalladino commented on src/components/admin/AdminProgramsTable.vue
> +    <div class="is-clearfix"></div>
@timparsons, did you add this in there?

2021-09-07 13:31 UTC, timparsons commented on src/components/admin/AdminProgramsTable.vue
> +    <div class="is-clearfix"></div>
Yep, I had to add that because the 'New ' button above the table has the `is-pulled-right` class, and this was causing an overlay to cover up the action buttons in the table. Doing the clearfix between the button and the table resolved that issue.

2021-09-07 13:46 UTC, dmeidlin approved these changes

2021-09-07 14:56 UTC, nickpalladino requested changes

2021-09-07 14:56 UTC, nickpalladino commented on src/components/trials/TrialsTable.vue
>      >
think this should have the clearfix between the button and table right?

2021-09-07 15:22 UTC, HMS17 commented on src/components/trials/TrialsTable.vue
>      >
Good catch; fixed

2021-09-07 15:24 UTC, nickpalladino approved these changes

2021-09-07 15:25 UTC, merged