Feature/bi 1060
Breeding-Insight/bi-web pull request #140
Opened 2021-10-29 18:16 UTC by davedrp

For https://breedinginsight.atlassian.net/browse/BI-1060

2021-11-05 15:49 UTC, timparsons requested changes
Looks great! Just had a few minor changes requested.  I also saw the build had failed due to linting errors.  Can you take a look at that, and correct that as well?

2021-11-05 15:49 UTC, timparsons commented on src/assets/scss/main.scss
> +  background-color: $warning-light;
Could you add a `border-left` similar to how the `.is-new` class is defined?  This would keep UI consistency with rows that are highlighted

2021-11-05 15:49 UTC, timparsons commented on src/components/tables/SidePanelTableRow.vue
> +//      AlertTriangleIcon,
Can you remove the commented out code?

2021-11-05 15:49 UTC, timparsons commented on src/components/tables/SidePanelTableRow.vue
> +        if (this.state.openedRow) {
very minor, but for code style, can the indentation of this if-statement be in line with the closing parenthesis?

2021-11-08 02:33 UTC, dmeidlin approved these changes

2021-11-11 20:15 UTC, merged