[BI-503] Add a loading indicator for Confirm Traits
Breeding-Insight/bi-web pull request #144
Opened 2021-11-09 17:15 UTC by HMS17

For both Germplasm and Trait Import, on clicking the "Confirm" button, the button will be disabled and a loading indicator will appear.

2021-11-10 14:28 UTC, timparsons requested changes

2021-11-10 14:28 UTC, timparsons commented on src/views/import/ImportTemplate.vue
> +    this.confirmImportState.bus.$emit(DataFormEventBusHandler.SAVE_STARTED_EVENT);
I would recommend putting this emit in the ConfirmImportMessageBox.vue `confirm` method

2021-11-10 17:02 UTC, HMS17 commented on src/views/import/ImportTemplate.vue
> +    this.confirmImportState.bus.$emit(DataFormEventBusHandler.SAVE_STARTED_EVENT);
Changed!

2021-11-10 17:24 UTC, timparsons approved these changes

2021-11-11 19:06 UTC, dmeidlin approved these changes

2021-11-11 20:28 UTC, merged