[BI-623] Update UI OntologyTables implementation to handle sort events
Breeding-Insight/bi-web pull request #146
Opened 2021-11-11 20:02 UTC by dmeidlin

This is a sub task for [BI-618](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-618).

The service and dao for Traits was changed to pass the query params used for sorting.
Vuex was used to store sort control state for each table. This was necessary to ensure that the display for a table is preserved when a user selects the other tab in the interface or when the user navigates to another list table.

The approach used here will be replicated for tables in the remaining sub tasks of [BI-618](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-618).

2021-11-12 17:32 UTC, timparsons requested changes

2021-11-12 17:32 UTC, timparsons commented on src/breeding-insight/model/Sort.ts
> +export enum TraitSortField {
I assume the intent of this file is to add more enums for sorting fields of different types?

2021-11-12 17:32 UTC, timparsons commented on src/breeding-insight/service/TraitService.ts
> +      if (sortOrder === undefined) sortOrder = SortOrder.Ascending;
If you wanted, you could set these default values in the parameters defined in the function signature.

2021-11-12 17:32 UTC, timparsons commented on src/store/sorting/getters.ts
> +    },
Why do the different columns have to be their own state for sort order?  Looks like there's one state for which field to sort on, so wondering if you could have one state for sort order.

2021-11-12 20:40 UTC, dmeidlin commented on src/store/sorting/getters.ts
> +    },
It's set up that way as a convenience for the user. If there is a preference to sort in different directions on different columns, you can switch back and forth between columns with one click, but that wasn't really a prime design consideration.  It was just easy enough to make it with the most general controls for the user.

2021-11-15 20:58 UTC, dmeidlin commented on src/breeding-insight/model/Sort.ts
> +export enum TraitSortField {
Yes, that's right.

2021-11-16 16:07 UTC, dmeidlin commented on src/store/sorting/getters.ts
> +    },
There isn't a way to have independent sort order states for each field using the Buefy sorting api, so I will change the ontology table to use a single sort order state as well to be consistent with the Buefy tables.

2021-11-19 17:09 UTC, ctucker3 requested changes
Code looks good. I have a few comments below on observations from running the code. I think only 1, 2 and 3 need your attention. 4 and 5 are probably more for @timparsons. 

1. Can we remove the underline on the arrow? See image below for traits list. Also, this icon is different from the other sorting icons, is this intentional?
![underlined_arrow](https://user-images.githubusercontent.com/17887341/142660573-12753852-3a38-4c13-b1ca-cc20c5e92409.png)

2. For the traits table, would it be possible to add an underline on the column like buefy does when you hover over it so the user knows they can interact with that column? 

3. For BI-618 sorting should be added to the trait confirmation page, but I don't see any sorting ability on that one. 

![no_sorting_trait_confirm](https://user-images.githubusercontent.com/17887341/142662102-a4f74e09-8d0b-41cd-bdca-ef2fed801fc1.png)

4. Looks like we need to fix the backend sorting. t11 should come before t10 here. (I'm not suggesting to do that in this card). 

![out_of_order_sorting](https://user-images.githubusercontent.com/17887341/142661625-fb0025dd-55cd-4599-bc7c-460aebc74f41.png)

5. I don't think this is a bug from your card, but I'll mark the bug here, just in case, since I see vuex changes in your code. When I create a new program, I get a success message. When I close that success message, it closes, but I get an error in the console:

```[Vue warn]: Computed property "isSuccessNotificationActive" was assigned to but it has no setter.```

2021-11-19 18:49 UTC, dmeidlin commented on src/breeding-insight/service/TraitService.ts
>              //TODO: Remove when backend default sorting is implemented
It looks like you ran under a prior commit; points 1 and 2 aren't an issue if you pull the latest commit 5f7ebfd. As for point 3, BI-618 calls for traits import preview to be sorted, which is what I changed and you can see it when navigating Ontology > Import Ontology, but the Ontology component is what's called when using Import File > Ontology, so you're right I should update that table as well. As for point 5, yeah I noticed the same while working on this and and agree that a bugfix card should be created.

2021-11-19 19:05 UTC, dmeidlin commented on src/breeding-insight/service/TraitService.ts
>              //TODO: Remove when backend default sorting is implemented
Actually, all of the ontology importing routes uses the same component, `TraitsImportTable.vue`, so there is nothing additional for me to do. Point 3 should also be fine once you pull the latest.

2021-11-19 19:53 UTC, timparsons requested changes

2021-11-19 19:53 UTC, timparsons commented on src/breeding-insight/model/Sort.ts
> +  flag: boolean;
I saw that this boolean indicated if it was ASC or DESC order, could the name of this field be either `ascending` or `descending` (whatever `true` means) OR change this field to be of type `SortOrder`?

2021-11-19 19:55 UTC, timparsons commented
@ctucker3 

> Looks like we need to fix the backend sorting. t11 should come before t10 here. (I'm not suggesting to do that in this card).

Yeah, a new card to handle this seems appropriate

2021-11-22 14:17 UTC, ctucker3 commented on src/breeding-insight/service/TraitService.ts
>              //TODO: Remove when backend default sorting is implemented
Oops, sorry about that! Just retested, 1 isn't an issue any more. 

2 still seems to be an issue, when I hover over a sortable column like `Method` that isn't currently being sorted, the pointer changes, but the header is not underlined like it usually is in the buefy table. The programs table displays the correct behavior. 

For 3, my initial comment isn't an issue anymore. However, on the trait import table, I can only switch to sort descending if I click directly on the icon, clicking on the header does not work. This seems to be the case for the Ontology list table as well. 

Also, for the TODO, could you check again? I still see it in the PR.

2021-11-22 19:48 UTC, dmeidlin commented on src/breeding-insight/model/Sort.ts
> +  flag: boolean;
Good idea, I changed the field to `order: SortOrder`.

2021-11-22 19:59 UTC, timparsons approved these changes

2021-11-23 17:58 UTC, dmeidlin commented on src/breeding-insight/service/TraitService.ts
>              //TODO: Remove when backend default sorting is implemented
Thanks for pointing out the hover state; I never noticed that on Buefy tables before! The ontology tables behave the same as the Buefy tables, now.

2021-11-23 18:03 UTC, ctucker3 approved these changes

2021-11-23 18:32 UTC, merged