[BI-1201] Add 'Program Key' field to Program Create
Breeding-Insight/bi-web pull request #147
Opened 2021-11-11 20:40 UTC by HMS17

TODO

Linked to PR TODO

2021-11-18 21:06 UTC, timparsons requested changes

2021-11-18 21:06 UTC, timparsons commented on src/breeding-insight/service/ProgramService.ts
> +            error['errorMessage'] = this.duplicateProgramKey;
This could be brittle if the text changes at all.  It may be worth looking into returning an enum for the status and evaluating that instead of a display string.

2021-11-18 21:16 UTC, HMS17 commented on src/breeding-insight/service/ProgramService.ts
> +            error['errorMessage'] = this.duplicateProgramKey;
That makes sense. I was using the statusText as an imperfect solution since this change broke the assumption that there'd be only one error type for each status code. Are there examples of returning an enum elsewhere in the codebase?

2021-11-19 14:03 UTC, timparsons commented on src/breeding-insight/service/ProgramService.ts
> +            error['errorMessage'] = this.duplicateProgramKey;
@HMS17 At the moment, no, there are no examples in the existing code for this.  Happy to talk through ways in which this could be done!

2021-11-19 19:56 UTC, timparsons approved these changes

2021-11-19 20:00 UTC, HMS17 commented on src/breeding-insight/service/ProgramService.ts
> +            error['errorMessage'] = this.duplicateProgramKey;
Implemented.

2021-11-22 13:57 UTC, ctucker3 approved these changes

2021-11-23 13:09 UTC, merged