[BI-1148] - Germplasm Import Table
Breeding-Insight/bi-web pull request #148
Opened 2021-11-16 14:44 UTC by ctucker3

Will need to implement the actual columns once we have the germplasm import working.

2021-11-18 15:03 UTC, dmeidlin approved these changes

2021-11-22 21:04 UTC, timparsons requested changes
I really like this reusable approach! See comments below.  

Also, the story in Jira needs to be updated to indicate the scope of work did not do anything with the backend and what to do if tested before the backend support is implemented.  Should also indicate what story will complete the backend work.

2021-11-22 21:04 UTC, timparsons commented on src/views/import/ImportGermplasm.vue
> +            <p>Total rows: {{ rows.length }}</p>
Story specifies this should say: "Total number of entries: n"

2021-11-22 21:04 UTC, timparsons commented on src/views/import/ImportGermplasm.vue
> +            <p>New Germplasm: {{ statistics.Germplasm.newObjectCount }}</p>
Story specifies this should say: "New germplasm count: n"

2021-11-23 14:52 UTC, ctucker3 commented on src/views/import/ImportGermplasm.vue
> +      'seedSource': 'Wild',
fixed

2021-11-23 14:52 UTC, ctucker3 commented on src/views/import/ImportGermplasm.vue
> +      'germplasmName': 'GID',
fixed

2021-11-23 14:52 UTC, ctucker3 commented on src/views/import/ImportGermplasm.vue
> +      'defaultDisplayName': 'Germplasm Name',
fixed

2021-11-23 14:52 UTC, ctucker3 commented on src/views/import/ImportGermplasm.vue
> +      'createdUser': 'Creator',
fixed

2021-11-23 14:57 UTC, ctucker3 commented on src/components/report/ReportExpandableDetails.vue
> +export default class ReportExpandableDetails extends Vue {
Since the array display is an extra for this card, I think it should be lefted out of the testing for now. The germplasm import won't have any array objects to display. When we add this card to the brapi importer tables we can add this to the testing since those will have good test cases. 

https://breedinginsight.atlassian.net/browse/BI-1240

2021-11-23 14:59 UTC, ctucker3 commented on src/views/import/ImportGermplasm.vue
> +            <p>Total rows: {{ rows.length }}</p>
fixed

2021-11-23 14:59 UTC, ctucker3 commented on src/views/import/ImportGermplasm.vue
> +            <p>New Germplasm: {{ statistics.Germplasm.newObjectCount }}</p>
fixed

2021-11-23 15:10 UTC, ctucker3 commented on src/breeding-insight/model/report/ImportFormatter.ts
> +      const field = displayColumn.split('.').join('_');
From what I see, those tables aren't using dot notation, but are passing through nested objects and then populating their own columns:

```
<b-table-column field="data.name" label="Name" sortable v-slot="props" :th-attrs="(column) => ({scope:'col'})">
        {{ props.row.data.name }}
</b-table-column>
```

I tried out dot notation again just now and it for some reason is can't match the header to the data, so the table doesn't get populated with data.

2021-11-23 15:41 UTC, ctucker3 commented on src/components/report/ReportTable.vue
> +      <template v-slot:details="row"></template>
I like that idea! The unflattened object is now passed through.

2021-11-23 15:41 UTC, ctucker3 commented on src/views/import/ImportGermplasm.vue
> +      'entryNumber': 'Entry No.'
Good catch, it was an issue sorting numbers. Fixed.

2021-11-23 15:59 UTC, ctucker3 commented on src/breeding-insight/model/report/ImportFormatter.ts
> +
For column toggle and 'n members':
https://breedinginsight.atlassian.net/browse/BI-1241

For general importer and multiple sibling expansion:
https://breedinginsight.atlassian.net/browse/BI-1240

Backend paging and show all columns was removed. Show all columns isn't a good feature addition, because its hard to tell whether columns are missing because there is no data, or because a column wasn't in an import. The backend paging doesn't have a use case yet, so I'll wait until we have a use case for that.

2021-11-30 03:10 UTC, timparsons approved these changes

2021-11-30 17:11 UTC, merged