Bug/bi 1158
Breeding-Insight/bi-web pull request #152
Opened 2021-11-23 13:56 UTC by davedrp

see https://breedinginsight.atlassian.net/browse/BI-1158

2021-11-23 18:11 UTC, ctucker3 requested changes

2021-11-23 18:11 UTC, ctucker3 commented on src/components/trait/TraitDetailPanel.vue
>          const synonyms = this.data.synonyms.slice(0, Math.min(this.data.synonyms.length, synonymsMaxLength)).join(", ");
Are all of these abbreviation changes intended for this card? The card you linked was only for the changed file template.

2021-11-23 18:24 UTC, ctucker3 commented
What branch of bi-api should I be running this on? When running on develop with the file below I get the error in the image:
[TraitsTest_BI1148.xls](https://github.com/Breeding-Insight/bi-web/files/7590280/TraitsTest_BI1148.xls)

![BI1158_failed_import](https://user-images.githubusercontent.com/17887341/143082358-f7789f43-9700-45a0-a4c3-3e013de5b59c.png)

2021-11-29 14:16 UTC, davedrp commented
> What branch of bi-api should I be running this on? When running on develop with the file below I get the error in the image: [TraitsTest_BI1148.xls](https://github.com/Breeding-Insight/bi-web/files/7590280/TraitsTest_BI1148.xls)
> 
> ![BI1158_failed_import](https://user-images.githubusercontent.com/17887341/143082358-f7789f43-9700-45a0-a4c3-3e013de5b59c.png)

**There is a bug/bi-1158 branch in bi-api**

2021-11-29 14:28 UTC, davedrp commented on src/components/trait/TraitDetailPanel.vue
>          const synonyms = this.data.synonyms.slice(0, Math.min(this.data.synonyms.length, synonymsMaxLength)).join(", ");
After a conversation with Tim, I removed all references to the abbreviation data element.  (I have now added a brief [comment](https://breedinginsight.atlassian.net/browse/BI-1158?focusedCommentId=12167) to the Jira story )

2021-11-29 15:48 UTC, ctucker3 approved these changes
Ran it with the bi-api BI-1158 branch and it worked as expected.

2021-11-29 19:34 UTC, dmeidlin commented on src/breeding-insight/model/Trait.ts
> +  //abbreviations?: Array<string>;
Looks like a line that was commented out initially and should now be deleted.

2021-12-06 20:47 UTC, davedrp commented on src/breeding-insight/model/Trait.ts
> +  //abbreviations?: Array<string>;
Deleted

2021-12-10 15:12 UTC, dmeidlin approved these changes

2021-12-15 16:50 UTC, merged