[BI-1249] Tags - Saving after <Cancel>
Breeding-Insight/bi-web pull request #154
Opened 2021-12-03 18:28 UTC by davedrp

[BI-1249](https://breedinginsight.atlassian.net/browse/BI-1249)

I noticed that Synonyms was having the same problem for the same reason, so I fixed that as well.

2021-12-03 18:57 UTC, ctucker3 requested changes

2021-12-03 18:57 UTC, ctucker3 commented on src/breeding-insight/model/Trait.ts
> +    }
I'm wondering if these array reassignments would be better done in the Trait constructor? With this method, I think we still run the danger of linking trait tags if we ever assign a new trait the values of another trait tags.

2021-12-03 18:57 UTC, ctucker3 commented on src/breeding-insight/model/Trait.ts
> +        (JSON.stringify(this.synonyms) === JSON.stringify(trait.synonyms)) &&
Will this be able to account for different ordering of the tags and synonyms?

2021-12-06 18:38 UTC, timparsons commented
Merged via #155 into releases/0.4

2021-12-06 18:38 UTC, closed without merging