Merge branch 'release/0.4' into develop
Breeding-Insight/bi-web pull request #157
Opened 2021-12-04 21:34 UTC by timparsons

2021-12-06 19:32 UTC, davedrp requested changes
Line 86 of src/breeding-insight/model/Trait.ts should be changed from 

this.tags = tags;
TO
 if (tags){
   this.tags = Array.from(tags);
 }

2021-12-06 20:53 UTC, timparsons commented
> Line 86 of src/breeding-insight/model/Trait.ts should be changed from
> 
> this.tags = tags; TO if (tags){ this.tags = Array.from(tags); }

@davedrp Fixed

2021-12-07 13:17 UTC, davedrp approved these changes

2021-12-07 21:19 UTC, nickpalladino approved these changes

2021-12-10 14:57 UTC, merged