[BI-1085] - Germplasm import user input
Breeding-Insight/bi-web pull request #164
Opened 2021-12-21 16:00 UTC by ctucker3

# Description
- Adds user inputs to the germplasm import during preview
- Adds user inputs to the brapi importer during preview

# Dependencies
- bi-api BI-1085

# Testing
- See bi-api BI-1085 for testing details.

2021-12-22 18:43 UTC, dmeidlin approved these changes

2021-12-23 15:48 UTC, timparsons requested changes
Happy path testing worked as expected.  I did try testing clicking the "Confirm" button with the import group name empty, and there was an error message of "An unknown error has occurred when uploading your import.", but the field in error wasn't highlighted.

2021-12-23 15:51 UTC, timparsons commented on src/views/import/ImportGermplasm.vue
> +                  v-bind:field-name="'Import Group Name'"
The wireframe has this labeled as "List Name"

2021-12-23 18:29 UTC, ctucker3 commented on src/views/import/ImportGermplasm.vue
> +                  v-bind:field-name="'Import Group Name'"
fixed

2021-12-23 18:30 UTC, ctucker3 commented
> I did try testing clicking the "Confirm" button with the import group name empty, and there was an error message of "An unknown error has occurred when uploading your import.", but the field in error wasn't highlighted.

The error banner now shows this:
![import_missing_field_error](https://user-images.githubusercontent.com/17887341/147279319-b4a89798-c69c-4e25-a99f-a919a7a855d3.png)

2021-12-23 19:15 UTC, timparsons approved these changes

2021-12-23 20:31 UTC, merged