[BI-1056] All Germplasm Table
Breeding-Insight/bi-web pull request #165
Opened 2022-01-05 15:53 UTC by ctucker3

# Description
**Story:** (https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1056)

Includes: 
- All germplasm table
- Germplasm navigation
- Germplasm lists navigation was included and the component will just have to be added in when ready. 

# Dependencies
sgn - BI-1056
bi-api - BI-1056

# Testing
Use the importer and the file below to import some germplasm. Play around with the table and try some paging out to make sure everything works. 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF.

2022-01-06 21:29 UTC, timparsons requested changes
The BrAPI models that were added are in the directory "brapps/reporter/model".  It might be better to move them to "brapi/model".

2022-01-06 21:29 UTC, timparsons commented on src/breeding-insight/service/BrAPIService.ts
> +import {Germplasm} from "@/breeding-insight/brapps/reporter/model/germplasm";
These imports aren't used and could be removed

2022-01-06 21:29 UTC, timparsons commented on src/views/germplasm/Germplasm.vue
> +            <a>Germplasm</a>
Per the story, this text should be "All Germplasm"

2022-01-06 21:29 UTC, timparsons commented on src/router/index.ts
> +          title: 'Germplasm',
Per the techspecs, this text should be "All Germplasm"

2022-01-06 21:29 UTC, timparsons commented on src/views/germplasm/GermplasmTable.vue
> +      Germplasm
This should probably be "All Germplasm" to match the nav

2022-01-10 14:09 UTC, ctucker3 commented on src/breeding-insight/service/BrAPIService.ts
> +import {Germplasm} from "@/breeding-insight/brapps/reporter/model/germplasm";
Removed

2022-01-10 14:09 UTC, ctucker3 commented on src/views/germplasm/Germplasm.vue
> +            <a>Germplasm</a>
Changed

2022-01-10 14:09 UTC, ctucker3 commented on src/router/index.ts
> +          title: 'Germplasm',
Changed

2022-01-10 19:01 UTC, timparsons approved these changes

2022-01-10 21:22 UTC, davedrp approved these changes

2022-01-12 15:08 UTC, merged