Feature/bi 1074
Breeding-Insight/bi-web pull request #167
Opened 2022-01-11 16:32 UTC by davedrp

# Description
**Story:** [BI-1074 - 1.4 Germplasm Import - Validate Breeding Methods](https://breedinginsight.atlassian.net/browse/BI-1074)

When Importing Germplasms, validate the breading methods against the breeding_method table.

# Dependencies
Must be run with bi-api branch _feature/BI-1074_.

# Checklist:

- [ x] I have performed a self-review of my own code
- [ x] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF.

2022-01-18 18:21 UTC, ctucker3 requested changes
The row numbers seem to be wrong. My errors are on row 2+ in this file, but the row numbers in the message start at 1. Here is my file: 
[BI-1074_bad_methods.xls](https://github.com/Breeding-Insight/bi-web/files/7891474/BI-1074_bad_methods.xls)

Here is the error: 
![screencapture-localhost-8080-programs-af970a5a-2b34-4225-b5b8-7dff83c18190-import-germplasm-2022-01-18-13_16_14](https://user-images.githubusercontent.com/17887341/149995909-d4e0785c-ff38-4408-9f81-e8dbcbbf33ce.png)

2022-01-18 18:21 UTC, ctucker3 commented on src/breeding-insight/service/ImportService.ts
> +  }
Right now you are returning:

```
progress: {
  errors: {
    rowErrors: [
      <errors>
    ]
  }
}
```

Does `errors` have a purpose? Could you remove `errors` and just return this like the traits import: 

```
progress: {
    rowErrors: [
      <errors>
    ]
}
```

2022-01-20 21:43 UTC, nickpalladino approved these changes

2022-02-07 13:31 UTC, ctucker3 commented
Also need to run TAF, so I'll approve after the title and TAF.

2022-02-08 13:43 UTC, davedrp commented
> Also need to run TAF, so I'll approve after the title and TAF.

Done

2022-02-08 17:04 UTC, ctucker3 approved these changes

2022-02-08 19:21 UTC, merged