[BI-1145] Add experiment import stub out
Breeding-Insight/bi-web pull request #172
Opened 2022-01-18 21:33 UTC by ctucker3

# Description
Adds a stub out of the experimental import. 

# Dependencies
develop on bi-api

# Testing
Go to the experimental import page. Download the template and verify.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF.

2022-01-19 16:15 UTC, HMS17 requested changes

2022-01-19 16:15 UTC, HMS17 commented on src/components/layouts/UserSideBarLayout.vue
> -                  <router-link v-bind:to="{name: 'ontology', params: {programId: activeProgram.id}}">
Would recommend running TAF in general, but particularly with navigation changes to ensure that it doesn't break scenarios.

2022-01-25 20:59 UTC, ctucker3 commented on src/views/import/ImportExperiment.vue
> +  <div id="import-germplasm">
changed

2022-01-25 21:00 UTC, ctucker3 commented on src/components/layouts/UserSideBarLayout.vue
> -                  <router-link v-bind:to="{name: 'ontology', params: {programId: activeProgram.id}}">
Ran TAF, results the same as develop branch.

2022-01-25 21:03 UTC, HMS17 approved these changes

2022-01-26 13:49 UTC, dmeidlin approved these changes

2022-01-26 14:09 UTC, merged