BI-1167 - Germplasm Import - Validate Required Fields
Breeding-Insight/bi-web pull request #175
Opened 2022-01-24 20:48 UTC by nickpalladino

# Description
**Story:** _Please include a link to the story in Jira_

_Please include a summary of the change that was made._

# Dependencies
_Please include any dependencies to other code branches, testing configurations, scripts to be run, etc._

# Testing
_Please include any details needed for reviewers to test this code_

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF.

2022-02-14 22:34 UTC, timparsons requested changes
Ran the following files through:

- Valid file - PASSED
- Missing columns - Error shows in the banner, not in the error section, but there's already a story for this ([BI-1324](https://breedinginsight.atlassian.net/browse/BI-1324))
- Missing required data - PASSED
- Column names in different cases - FAILED - file -> [germplasm_column_casing.xls](https://github.com/Breeding-Insight/bi-web/files/8064404/germplasm_column_casing.xls)

2022-02-15 13:58 UTC, ctucker3 requested changes
Overall looks good! Just a few small questions/requests.

2022-02-15 13:58 UTC, ctucker3 commented on src/views/import/ImportTemplate.vue
> +        if(this.import_errors==null) {
Should this be an `undefined` check? I don't see anywhere in the `parseError` method where null is returned.

2022-02-15 13:58 UTC, ctucker3 commented on src/views/import/ImportTemplate.vue
> +          this.$emit('show-error-notification', `Errors: ${e.response!.progress!.message!}`);
What if there is no error message? (not sure if this case can ever happen)

2022-02-15 15:21 UTC, nickpalladino commented on src/views/import/ImportTemplate.vue
> +        if(this.import_errors==null) {
Good point, this was copied over from a previous section that did have a null being returned. Maybe it doesn't need any check and the FileSelectMessageBox component can just display unknown error when import_errors doesn't have any validation errors?

2022-02-15 15:22 UTC, nickpalladino commented on src/views/import/ImportTemplate.vue
> +          this.$emit('show-error-notification', `Errors: ${e.response!.progress!.message!}`);
Based on the previous comment I think maybe this check should just be removed.

2022-02-15 15:44 UTC, ctucker3 commented on src/views/import/ImportTemplate.vue
> +        if(this.import_errors==null) {
Sounds good to me!

2022-02-15 15:44 UTC, ctucker3 commented on src/views/import/ImportTemplate.vue
> +          this.$emit('show-error-notification', `Errors: ${e.response!.progress!.message!}`);
Sounds good!

2022-02-15 16:12 UTC, nickpalladino commented on src/views/import/ImportTemplate.vue
> +        if(this.import_errors==null) {
Check has been removed.

2022-02-16 13:35 UTC, timparsons approved these changes

2022-02-17 13:51 UTC, ctucker3 approved these changes

2022-02-17 14:18 UTC, merged