[BI-1288] Trait column on Ontology List page should be concatenation of trait entity + attribute
Breeding-Insight/bi-web pull request #181
Opened 2022-02-07 21:30 UTC by dmeidlin

# Description
[BI-1288](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1288)

Active and archived ontology lists as well as ontology import preview tables updated to show trait columns as entity + attribute.

# Dependencies
bi-api `develop`

# Testing

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2022-02-09 19:53 UTC, HMS17 approved these changes

2022-02-22 14:50 UTC, nickpalladino commented
Think this should be targeting the v0.5 release branch right?

2022-02-22 15:34 UTC, nickpalladino commented
Is captialization of only the attribute part what was desired? Can't tell from the card.

2022-02-22 15:35 UTC, nickpalladino requested changes
Think target branch should be changed and left comment about capitalization.

2022-02-22 22:16 UTC, nickpalladino approved these changes

2022-02-22 22:37 UTC, merged