[BI-1356] Ordinal Nominal Switching Errors
Breeding-Insight/bi-web pull request #194
Opened 2022-02-25 21:38 UTC by HMS17

# Description
**Story:**[ISSUE: New/Edit Term - Switching between scale classes, specifically ordinal and nominal, not working properly](https://breedinginsight.atlassian.net/browse/BI-1356)

_Please include a summary of the change that was made._

# Dependencies
_Please include any dependencies to other code branches, testing configurations, scripts to be run, etc._

# Testing
_Please include any details needed for reviewers to test this code_

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2022-03-09 19:07 UTC, timparsons requested changes
One small change request

2022-03-09 19:07 UTC, timparsons commented on src/components/ontology/OntologyTable.vue
> +      if ((traitToSave) && (traitToSave.scale) && (traitToSave.scale.dataType) && (Scale.dataTypeEquals(traitToSave.scale.dataType, DataType.Nominal)) && (traitToSave.scale.categories)) {
Minor thing, but it might be worth creating a method like `prepareScaleCategoriesForSave`, and have everything in this `if` block be in that method.  You could then call this new method from both `updateTrait` and `saveTrait`

2022-03-09 19:40 UTC, HMS17 commented on src/components/ontology/OntologyTable.vue
> +      if ((traitToSave) && (traitToSave.scale) && (traitToSave.scale.dataType) && (Scale.dataTypeEquals(traitToSave.scale.dataType, DataType.Nominal)) && (traitToSave.scale.categories)) {
Good point, implemented!

2022-03-09 20:01 UTC, timparsons approved these changes

2022-03-14 18:34 UTC, ctucker3 requested changes
Looks like this new code switches label and value for ordinal values. If I do, Test1 = 1 and Test2 = 2 on this code branch and qa-test they give two different results. Attaching screen shots of json from both. 

Local:
![screencapture-jsonviewer-stack-hu-2022-03-14-14_29_51](https://user-images.githubusercontent.com/17887341/158238412-03355a39-c85c-4b18-ace9-e25cb23c2758.png)

QA Test:
![screencapture-jsonviewer-stack-hu-2022-03-14-14_34_13](https://user-images.githubusercontent.com/17887341/158238452-e2f9e2db-9ca5-4a19-825b-483906344000.png)

2022-03-14 19:36 UTC, ctucker3 approved these changes
Chatted with Heather. My reported error looks to have been a mistake with testing.

2022-03-14 19:38 UTC, ctucker3 approved these changes

2022-03-14 20:03 UTC, merged