[BI-1339] Germplasm Details page
Breeding-Insight/bi-web pull request #217
Opened 2022-04-05 16:08 UTC by HMS17

# Description
**Story:** _Please include a link to the story in Jira_

_Please include a summary of the change that was made._

# Dependencies
_Please include any dependencies to other code branches, testing configurations, scripts to be run, etc._

# Testing
_Please include any details needed for reviewers to test this code_

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2022-04-11 14:46 UTC, ctucker3 requested changes

2022-04-11 14:46 UTC, ctucker3 commented on src/breeding-insight/dao/GermplasmDAO.ts
> +        config.params = {}; //todo check if needed
Still a TODO?

2022-04-11 14:46 UTC, ctucker3 commented on src/breeding-insight/dao/GermplasmDAO.ts
> +    }
Most of our new services use async methods for the service and daos, making the calls look more like this:

```
const { data } = await api.call(config) as Response;
return new BiResponse(data);
```

Then you catch the error in the service with a try/catch.

2022-04-11 14:46 UTC, ctucker3 commented on src/breeding-insight/service/GermplasmService.ts
>  }
Can make this an async method as well.

2022-04-11 14:46 UTC, ctucker3 commented on src/breeding-insight/service/GermplasmService.ts
> +                reject();
Might be good to have a rejection reason in case we ever need to debug this.

2022-04-11 14:46 UTC, ctucker3 commented on src/views/germplasm/GermplasmDetails.vue
> +    <p></p>
Maybe a class of `mb-4` instead of the empty `<p></p>` on the router-link if you're going for spacing?

2022-04-11 14:46 UTC, ctucker3 commented on src/views/germplasm/GermplasmDetails.vue
> +  }
Could be useful on Germplasm model.

2022-04-11 14:46 UTC, ctucker3 commented on src/views/germplasm/GermplasmTable.vue
> +  }
Could be useful on Germplasm model.

2022-04-13 17:37 UTC, ctucker3 approved these changes

2022-04-13 21:06 UTC, timparsons requested changes
Need to run the code still, but one suggested change

2022-04-13 21:06 UTC, timparsons commented on .env.development
> +VUE_APP_BI_REFERENCE_SOURCE=breeding-insight.org
can this be changed to `breedinginsight.org`

2022-04-14 20:00 UTC, timparsons approved these changes
Testing passed

2022-04-14 22:48 UTC, merged