[BI-1375] - Make GIDs clickable links
Breeding-Insight/bi-web pull request #218
Opened 2022-04-13 14:10 UTC by HMS17

# Description
**Story:** [BI-1375 - Make GIDs clickable links](https://breedinginsight.atlassian.net/browse/BI-1375)

_Please include a summary of the change that was made._

# Dependencies
_Please include any dependencies to other code branches, testing configurations, scripts to be run, etc._

# Testing
_Please include any details needed for reviewers to test this code_

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2022-04-21 14:49 UTC, ctucker3 requested changes

2022-04-21 14:49 UTC, ctucker3 commented on src/components/germplasm/GermplasmLink.vue
> +    </router-link>
I'm wondering for this if it would be better to have the GID not be a link if UUID isn't provided, rather than not showing the GID at all? 

I'm thinking that because from a user perspective it might be better to have a broken link rather than missing data in the case of a data error such as missing UUID.

2022-04-21 14:49 UTC, ctucker3 commented on src/views/germplasm/GermplasmDetails.vue
> +          <template v-if="Pedigree.parsePedigreeString(germplasm.pedigree).maleParent">
In the GermplasmLink above you have the `v-if` directly in the component, but here you have it in a `template`. Is it possible to move this into the GermplasmLink for consistency?

2022-04-21 14:49 UTC, ctucker3 commented on src/views/germplasm/GermplasmTable.vue
> +      <b-table-column field="externalReferences" v-slot="props" :th-attrs="(column) => ({scope:'col'})">
Wouldn't this field be something like `showDetails`?

2022-05-03 15:21 UTC, HMS17 commented on src/components/germplasm/GermplasmLink.vue
> +    </router-link>
Good point, changed to be text in the case of no UUID

2022-05-03 15:22 UTC, HMS17 commented on src/views/germplasm/GermplasmTable.vue
> +      <b-table-column field="externalReferences" v-slot="props" :th-attrs="(column) => ({scope:'col'})">
Based on discussion with Tim, confusion resolved by removing the field as it is unneeded here.

2022-05-03 15:26 UTC, HMS17 commented on src/views/germplasm/GermplasmDetails.vue
> +          <template v-if="Pedigree.parsePedigreeString(germplasm.pedigree).maleParent">
Right now I have the GermplasmLink as a one germplasm per link sort of thing rather than a more complicated component that includes multiple configurations of links. The v-if here is wrapped around the "/ <male parent GID>" part of the pedigree since the slash and gid only show up if there is a male parent. I could add some sort of boolean to pass in but I would still need a boolean on the outside for the slash lest I make the Germplasm Link more complicated by adding the slash. So what I have now seems to be the simplest route?

2022-05-03 19:39 UTC, ctucker3 approved these changes

2022-05-03 19:39 UTC, ctucker3 commented on src/views/germplasm/GermplasmDetails.vue
> +          <template v-if="Pedigree.parsePedigreeString(germplasm.pedigree).maleParent">
Ah gotcha, I missed the `/`. No need to change anything, thanks for the explanation!

2022-05-11 16:15 UTC, merged