[BI-1191] Germplasm Search
Breeding-Insight/bi-web pull request #242
Opened 2022-06-21 18:07 UTC by ctucker3

# Description
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1191

- Added filtering support to ExpandableTable.
- Added filtering to Germplasm Table. 
- Modify table loading behavior so only table rows were greyed out and user can still interact with filter fields. 
- Added a `CallStack` class that could be a good replacement for current pagination request behavior. 

# Dependencies
biapi: BI-1191

# Testing
See biapi PR. 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2022-06-22 22:32 UTC, HMS17 requested changes

2022-06-22 22:32 UTC, HMS17 commented on src/views/germplasm/GermplasmTable.vue
> +      if (this.paginationController.showAll) {
I removed this if statement block as part of BI-1401 which among other things switched GermplasmTable from using PaginationController to using BackendPaginationController, which handled update of the paginationcontroller values. Is there a particular reason why this code was reinstated, and should that function maybe be part of BackendPaginationController instead so it doesn't get repeated across multiple tables?

2022-06-23 19:28 UTC, timparsons approved these changes
Approving this with the assumption that Heather's comment will be resolved

2022-06-27 13:08 UTC, ctucker3 commented on src/views/germplasm/GermplasmTable.vue
> +      if (this.paginationController.showAll) {
That section had a merge conflict, so I think it was probably reintroduced from there. Thanks for catching that! I'll look into removing it.

2022-06-27 13:26 UTC, ctucker3 commented on src/views/germplasm/GermplasmTable.vue
> +      if (this.paginationController.showAll) {
I removed that if statement and tested it to make sure the pagination still works. Everything still works!

2022-07-13 17:20 UTC, nickpalladino approved these changes

2022-07-13 20:09 UTC, merged