[BI-1199] - Choose file format for germplasm export
Breeding-Insight/bi-web pull request #243
Opened 2022-06-21 18:45 UTC by HMS17

# Description
**Story:** [BI-1199 - Choose file format for germplasm export](https://breedinginsight.atlassian.net/browse/BI-1199)

Changes to frontend to enable modal selection of file type when downloading germplasm list and passing of user selection to backend.

Added new reusable modal component SelectModal that takes in title and a list of options to display, and utilized it to display file types upon user clicking download and pass that information on click.

# Dependencies
[bi-api/BI-1199](https://github.com/Breeding-Insight/bi-api/pull/193)

# Testing
- Open Germplasm List
- Click Download
- Verify modal pops up and shows
- Verify each file type can be selected
- Verify when cancel clicked the modal closes and nothing is downloaded
- Verify for each file type (csv, xls, xlsx) that when it is selected and download is clicked the file is downloaded with the proper extension and the correct data

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have tested my code and ensured it meets the acceptance criteria of the story
- [X] I have create/modified unit tests to cover this change
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to documentation
- [X] I have run TAF: [_\<link to TAF run>_](https://github.com/Breeding-Insight/taf/actions/runs/2545220951)

2022-06-23 19:27 UTC, timparsons requested changes

2022-06-23 19:27 UTC, timparsons commented on src/components/modals/SelectModal.vue
> +        <slot></slot>
I would recommend naming this slot because the main content of the modal (the radio buttons) is not what goes into this slot.

2022-06-23 19:27 UTC, timparsons commented on src/components/modals/SelectModal.vue
> +  subtitle!: string;
Does `subtitle` have to be required?

2022-06-24 22:37 UTC, HMS17 commented on src/components/modals/SelectModal.vue
> +        <slot></slot>
Good point, named

2022-06-24 22:37 UTC, HMS17 commented on src/components/modals/SelectModal.vue
> +  subtitle!: string;
Nope, changed!

2022-06-30 19:18 UTC, davedrp approved these changes

2022-07-06 17:08 UTC, ctucker3 approved these changes
Works as expected

2022-07-06 17:37 UTC, timparsons approved these changes

2022-07-06 17:43 UTC, merged