[BI-1230] Truly Unknown Germplasm
Breeding-Insight/bi-web pull request #260
Opened 2022-08-17 19:43 UTC by HMS17

# Description
**Story:** [BI-1230 - Truly Unknown Germplasm](https://breedinginsight.atlassian.net/browse/BI-1230)

_Please include a summary of the change that was made._

# Dependencies
_Please include any dependencies to other code branches, testing configurations, scripts to be run, etc._

# Testing
_Please include any details needed for reviewers to test this code_

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2022-09-15 19:40 UTC, timparsons requested changes
Dev testing passed.  Code looks good with one minor change request

2022-09-15 19:40 UTC, timparsons commented on src/breeding-insight/model/import/germplasm/Pedigree.ts
> +  public static parsePedigreeStringWithUnknowns(pedigreeString: string, femaleParentUnknown: string, maleParentUnknown: string, gid: string) : Pedigree {
It looks like the `femaleParentUnknown` and `maleParentUnknown` additionalInfo fields are booleans.  Can the types of the parameters in this method can be updated to reflect this?

2022-09-16 15:51 UTC, HMS17 commented on src/breeding-insight/model/import/germplasm/Pedigree.ts
> +  public static parsePedigreeStringWithUnknowns(pedigreeString: string, femaleParentUnknown: string, maleParentUnknown: string, gid: string) : Pedigree {
Vue yells at me if I change the parameter type to boolean despite it being very clearly processed as a boolean in the method. It is strange.

2022-09-16 17:13 UTC, timparsons approved these changes

2022-09-16 17:13 UTC, timparsons commented on src/breeding-insight/model/import/germplasm/Pedigree.ts
> +  public static parsePedigreeStringWithUnknowns(pedigreeString: string, femaleParentUnknown: string, maleParentUnknown: string, gid: string) : Pedigree {
Ok, thanks for looking into this!

2022-09-21 15:12 UTC, nickpalladino approved these changes

2022-09-21 15:18 UTC, merged