[BI-1147] ﻿﻿2.0 Experimental Data Preview Universal Elements
Breeding-Insight/bi-web pull request #273
Opened 2022-10-07 14:50 UTC by dmeidlin

# Description
**Story:** [BI-1147](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1147)

a class was added to the germplasm names in new experiment import preview so that it can be styled light purple.
created by/date fields in experiment details of the preview are only displayed if importing a new experiment with new observation units.

# Dependencies
bi-api develop

# Testing

create a new experiment and verify preview summary and table meet the acceptance criteria.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2022-10-11 19:05 UTC, davedrp commented on src/views/import/ImportExperiment.vue
> +            <p v-if="isExisting(rows)">User: </p>
The User Data will never be displayed.

2022-10-11 19:14 UTC, davedrp requested changes

2022-10-11 19:14 UTC, davedrp commented on src/views/import/ImportExperiment.vue
> +    return rows.length && rows[0].trial.state === ImportObjectState.EXISTING && rows[0].observationUnit.state === ImportObjectState.EXISTING;
The requirement only specifies that the Experiment already Exist (not the observation unit.  
Also, at this point, I think all observation Units are assumed to be new.

2022-10-13 23:37 UTC, timparsons requested changes
### Testing

Test A
1. Imported germplasm
2. Imported experiment file with GIDs created in step 1
3. Verified preview did not show created date or created by
4. Verified the preview message appeared -> FAIL -> Techspecs mention adding an information message above the import stats
5. Confirmed import

Test B
1. Uploaded the same file from step two
2. Validated created date and created by displayed in import stats -> FAIL -> neither field was displayed

2022-10-19 16:57 UTC, timparsons approved these changes

2022-10-19 19:39 UTC, davedrp approved these changes

2022-10-31 17:47 UTC, merged