[BI-1129] View Germplasm List
Breeding-Insight/bi-web pull request #276
Opened 2022-11-02 17:43 UTC by dmeidlin

# Description
**Story:** [BI-1129](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1129)

- `GermplasmService.getAllInList()` created to fetch all germplasm in a given list
- `src/views/germplasm/GermplasmByList.vue` created for displaying list details
- `src/views/germplasm/GermplasmTable.vue`was renamed to `src/views/germplasm/AllGermplasm.vue`
- The germplasm table in `src/views/germplasm/AllGermplasm.vue` was factored out into a new component `src/components/germplasm/GermplasmTable.vue`
- 'src/views/germplasm/AllGermplasm' refactored to use `src/components/germplasm/GermplasmTable`
- the download button and modal was factored out of `src/components/germplasm/GermplasmListsTable.vue` into a new component, `src/components/germplasm/GermplasmDownloadButton`
- `src/components/germplasm/GermplasmListsTable,vue` refactored to use new download button component

# Dependencies
`feature/BI-1129` branch of bi-api

# Testing
- Import germplasm and navigate the germplasm lists table.
- Select the "Details" link on a row in the table
- Verify that the details displayed match the wireframe and spec

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2022-11-03 14:39 UTC, timparsons requested changes
Germplasm list detail page looks great!!

One small issue I was seeing while testing was that changing the page size on either the `AllGermplasm` table or the `GermplasmByList` table was not updating the number of records per page in the table.

Have a few smaller code changes as well

2022-11-03 14:39 UTC, timparsons commented on src/components/germplasm/GermplasmListsTable.vue
> +import GermplasmDownloadButton from '@/components/germplasm/GermplasmDownloadButton';
Typescript is complaining about this import.  Adding `.vue` to the end of the path resolved this

2022-11-03 15:00 UTC, HMS17 reviewed
Approving on assumption Tim's comments are addressed. Also, might be good to run TAF to assess if a card needs to be made to change scenarios in response to UI changes.

2022-11-08 18:00 UTC, dmeidlin commented on src/components/germplasm/GermplasmTable.vue
> +    //     { pageSize: this.paginationController.pageSize, page: this.paginationController.currentPage - 1 }, filters));
Yep! gone.

2022-11-08 18:00 UTC, dmeidlin commented on src/views/germplasm/GermplasmByList.vue
> +import GermplasmDownloadButton from '@/components/germplasm/GermplasmDownloadButton';
done

2022-11-08 18:01 UTC, dmeidlin commented on src/components/germplasm/GermplasmTable.vue
> +  germplasmFetch!: (programId: string, sort: GermplasmSort, pageSize: number, page: number) => () => Promise<BiResponse>;
done

2022-11-08 18:07 UTC, dmeidlin commented
> Germplasm list detail page looks great!!
> 
> One small issue I was seeing while testing was that changing the page size on either the `AllGermplasm` table or the `GermplasmByList` table was not updating the number of records per page in the table.
> 
> Have a few smaller code changes as well

The issue was in having page and pageSize passed in as values to germplasmFetch(). It's fixed now by passing in a reference to the paginationController, instead.

2022-11-09 17:03 UTC, dmeidlin commented
> Approving on assumption Tim's comments are addressed. Also, might be good to run TAF to assess if a card needs to be made to change scenarios in response to UI changes.

The smoke tests pass. The full test throw errors that appear unrelated to changes made in this branch.

2022-11-10 02:39 UTC, timparsons approved these changes
Testing passed

2022-11-14 14:30 UTC, HMS17 approved these changes

2022-11-14 14:49 UTC, merged