[BI-1194] - Upload with timestamps
Breeding-Insight/bi-web pull request #281
Opened 2022-11-15 21:16 UTC by HMS17

# Description
**Story:** [BI-1194 - Upload with timestamps](https://breedinginsight.atlassian.net/browse/BI-1194)

_Please include a summary of the change that was made._

# Dependencies
_Please include any dependencies to other code branches, testing configurations, scripts to be run, etc._

# Testing
_Please include any details needed for reviewers to test this code_

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2022-11-22 13:38 UTC, davedrp approved these changes

2022-11-29 18:40 UTC, timparsons requested changes

2022-11-29 18:40 UTC, timparsons commented on src/views/import/ImportExperiment.vue
> +            <p v-else>{{ props.row.data.observations.filter(observation => observation.brAPIObject.observationVariableName === variable)[0].brAPIObject.value }}</p>
I'd suggest making functions to handle fetching the timestamp and value instead of doing it in line here

2022-11-29 20:40 UTC, timparsons approved these changes

2022-11-29 20:55 UTC, merged