feature/BI-1650
Breeding-Insight/bi-web pull request #282
Opened 2022-11-16 03:19 UTC by timparsons

# Description
**Story:** https://breedinginsight.atlassian.net/browse/BI-1650

- Created  a component for importing genotype data on the Import Data page
- Created a component for displaying genotype data on the germplasm detail page
- Added BrAPI models for Genotype v2.1

# Dependencies
bi-api/feature/BI-1650

# Testing
Test the card following the acceptance criteria in the card

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [x] I have create/modified unit tests to cover this change
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2023-01-20 20:38 UTC, dmeidlin approved these changes

2023-02-27 21:14 UTC, timparsons commented on src/views/import/ImportGeno.vue
> +                &lt;something to go here&gt;
Done

2023-02-27 21:25 UTC, nickpalladino requested changes

2023-02-27 21:25 UTC, nickpalladino commented on src/views/import/ImportGeno.vue
> +                ensure that Sample IDs match to an Exp Unit ID within the chosen experiment
Sorry to be a pain but could the sentence be capitalized to be consistent with the formatting in the other imports?

2023-02-28 00:18 UTC, timparsons commented on src/views/import/ImportGeno.vue
> +                ensure that Sample IDs match to an Exp Unit ID within the chosen experiment
Done

2023-02-28 14:28 UTC, nickpalladino approved these changes

2023-03-01 20:44 UTC, merged