BI-1616
Breeding-Insight/bi-web pull request #293
Opened 2023-01-10 21:32 UTC by nickpalladino

# Description
**Story:** _Please include a link to the story in Jira_

_Please include a summary of the change that was made._

# Dependencies
_Please include any dependencies to other code branches, testing configurations, scripts to be run, etc._

# Testing
_Please include any details needed for reviewers to test this code_

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2023-01-11 21:53 UTC, timparsons approved these changes
Looks good!

2023-01-13 16:51 UTC, dmeidlin requested changes
The message displayed, "Germplasm lists not yet specified", when the filter input doesn't match any lists doesn't seem right. Can we change it to something like, "No matching lists found"?

2023-01-13 18:28 UTC, nickpalladino commented
> The message displayed, "Germplasm lists not yet specified", when the filter input doesn't match any lists doesn't seem right. Can we change it to something like, "No matching lists found"?

What if there are no germplasm lists and it's not just no filter matches? Should it be some combination like "Germplasm list not yet specified or no matching lists found"?

2023-01-13 19:14 UTC, nickpalladino commented
> > The message displayed, "Germplasm lists not yet specified", when the filter input doesn't match any lists doesn't seem right. Can we change it to something like, "No matching lists found"?
> 
> What if there are no germplasm lists and it's not just no filter matches? Should it be some combination like "Germplasm lists not yet specified or no matching lists found"?

I pushed those changes.

2023-01-13 21:30 UTC, dmeidlin approved these changes

2023-01-18 19:37 UTC, merged