[BI-1606] Allow germplasm records to be in multiple lists
Breeding-Insight/bi-web pull request #298
Opened 2023-01-26 17:05 UTC by dmeidlin

# Description
**Story:** [BI-1606](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1606)

The germplasm list details page now uses a helper function to display the entry number whether the number is stored using the old format of importEntryNumber or using the listEntryNumbers map.

# Dependencies
bi-api feature/BI-1606 branch

# Testing
1. Import germplasm with user-supplied entry numbers. 
2. Go to the Germpasm Lists tab and use the dev tools console to inspect the list object in the response and verify there is an external reference entry for /lists and note the UUID stored as the refernceID.
3. Then view all imported germplasm and use the dev tools console to inspect the germplasm objects in the response from bi-api. Verify the additionalInfo field "listEntryNumbers" exists and the value is a Map with the imported list ID from step 2 as the key and entry number as value.

4. Import germplasm without user-supplied entry numbers and repeat process above.

5. Download the imported germplasm and verify the exported file records match what is stored.
6. Download a list of previously imported germplasm that store entry number values in additionalInfo.imortEntryNumber and verify the exported file records match what is stored.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have tested that my code works with both the brapi-java-server and BreedBase
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: [#136](https://github.com/Breeding-Insight/taf/actions/runs/3526754134)

2023-01-31 16:19 UTC, davedrp approved these changes

2023-02-01 14:59 UTC, timparsons requested changes

2023-02-01 14:59 UTC, timparsons commented on src/views/germplasm/GermplasmByList.vue
> +      return ref.referenceSource == "breeding-insight.net/lists" ? ref.referenceID : result;
the reference source root (aka `breeding-insight.net` in this line of code) is an environment variable: `VUE_APP_BI_REFERENCE_SOURCE`

2023-02-02 20:50 UTC, timparsons requested changes
Code looks good, but when I was testing, sorting by entry number was not working correctly

2023-02-07 19:37 UTC, timparsons approved these changes
Working as expected!

2023-02-09 21:21 UTC, merged