[BI-1617] Refactor Ontology table to use Buefy
Breeding-Insight/bi-web pull request #304
Opened 2023-03-03 18:52 UTC by dmeidlin

# Description
**Story:** [BI-1617](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1617), [BI-1628](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1628), [BI-1629](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1629)

# Dependencies
bi-api `feature/BI-1629`

# Testing
_Please include any details needed for reviewers to test this code_

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2023-03-03 22:43 UTC, timparsons requested changes
Code looks good! Couple of small questions.

2023-03-03 22:43 UTC, timparsons commented on src/breeding-insight/service/TraitService.ts
> +      const { data } = await api.call(config) as Response;
I think this should be moved to the `TraitDAO`

2023-03-03 22:43 UTC, timparsons commented on src/components/tables/SidePanelTableBuefy.vue
> +            </b-table-column>
Looks like this column was copied from the `ExpandableTable`.  Is it needed in this component?

2023-03-03 22:43 UTC, timparsons commented on src/components/tables/SidePanelTableBuefy.vue
> +            </template>
Looks like this column was copied from the `ExpandableTable`. Is it needed in this component?

2023-03-08 21:21 UTC, davedrp approved these changes

2023-03-08 21:57 UTC, timparsons requested changes
Sorry, a couple more questions

2023-03-08 21:57 UTC, timparsons commented on src/breeding-insight/service/TraitService.ts
> +  }
Curious as to why this block of code is in the service and not the DAO?

2023-03-08 21:57 UTC, timparsons commented on src/components/ontology/OntologyTable.vue
> +    <SidePanelTableNew
Is the intent to rename this back to `SidePanelTable` once the old version has been completely removed from the codebase?

2023-03-10 15:54 UTC, timparsons approved these changes

2023-03-10 20:37 UTC, merged