BI-1717 (View experiment: Details, Summary Stats, Actions)
Breeding-Insight/bi-web pull request #316
Opened 2023-05-23 17:44 UTC by davedrp

# Description
**Story:** [BI-1716](https://breedinginsight.atlassian.net/browse/BI-1717) Sub-story of [BI-1644](https://breedinginsight.atlassian.net/browse/BI-1644) View experiment: Details, Summary Stats, Actions

- Created ExperimentDAO.ts and ExperimentService.ts to fetch an individual experiment
- Created ExperimentDetails.vue to display an Experiments details.

# Dependencies
**bi-api**: feature/BI-1716 branch

# Testing
(See _Acceptance Criteria_ in [BI-1644])

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [X] I have run TAF: _\<link to TAF run>_

2023-05-24 20:09 UTC, timparsons requested changes
Just a couple of minor changes

2023-05-24 20:09 UTC, timparsons commented on src/components/experiments/ExperimentsObservationsTable.vue
> +<!--        </router-link>-->
Sounds good.  I think this commented code should be removed then.

2023-05-24 20:09 UTC, timparsons commented on src/views/germplasm/GermplasmDetails.vue
> +    // console.log(next);
Can these lines be removed?

2023-05-24 20:09 UTC, timparsons commented on src/views/germplasm/GermplasmDetails.vue
> +    console.log("-------mount----------");
Can this line be removed?

2023-05-24 20:09 UTC, timparsons commented on src/views/germplasm/GermplasmDetails.vue
> +
Can these lines be removed?

2023-05-25 19:13 UTC, timparsons approved these changes

2023-05-26 15:24 UTC, dmeidlin commented on src/breeding-insight/model/Trial.ts
> +  //datasetAuthorships?: Array<TrialNewRequestDatasetAuthorships>;
Remove the commented out fields if not needed

2023-05-26 15:32 UTC, dmeidlin commented on src/breeding-insight/utils/BrAPIUtils.ts
> +    static getBreedingInsightId(references: ExternalReferences, referenceSourcePath: string = ""): string | undefined {
Instead of typing the source as string with an empty string as default, would you mind making an ExternalReferenceSource enum and specify the arg as non-null?

2023-05-26 15:33 UTC, timparsons commented on src/breeding-insight/model/Trial.ts
> +  //datasetAuthorships?: Array<TrialNewRequestDatasetAuthorships>;
@dmeidlin I think they are commented out because the `Contact` and `TrialNewRequestDatasetAuthorships` types 
aren't in the code base, but these fields are a part of the BrAPI Trial model.  Are you ok with leaving them in there with this in mind?

2023-05-26 15:34 UTC, dmeidlin commented on src/components/trait/TraitDetailPanel.vue
> +        console.log(synonyms);
a leftover console.log statement that needs to be deleted

2023-05-26 15:36 UTC, timparsons commented on src/breeding-insight/utils/BrAPIUtils.ts
> +    static getBreedingInsightId(references: ExternalReferences, referenceSourcePath: string = ""): string | undefined {
This method was copied from `GermplasmUtils`.  I think there are places in the code that don't specify a `referenceSourcePath` parameter (because it's intended to just be `breedinginsight.org`) hence why there is a default of an empty string.

2023-05-26 15:48 UTC, timparsons commented on src/components/trait/TraitDetailPanel.vue
> +        console.log(synonyms);
Removed

2023-05-26 16:03 UTC, dmeidlin commented on src/breeding-insight/model/Trial.ts
> +  //datasetAuthorships?: Array<TrialNewRequestDatasetAuthorships>;
Yep, np.

2023-05-26 16:04 UTC, dmeidlin commented on src/breeding-insight/utils/BrAPIUtils.ts
> +    static getBreedingInsightId(references: ExternalReferences, referenceSourcePath: string = ""): string | undefined {
Ah, I see. I'm fine leaving it as is, then.

2023-06-05 14:54 UTC, dmeidlin approved these changes

2023-06-05 17:36 UTC, merged