[BI-1923] Treatment factor missing from experimental ui
Breeding-Insight/bi-web pull request #332
Opened 2023-09-21 19:39 UTC by davedrp

# Description
**Story:** [BI-1923](https://breedinginsight.atlassian.net/browse/BI-1923) - Treatment factor missing from experimental ui

# Dependencies
bi-api: develop branch

# Testing
Import an experiment with treatment factor.  
Display it.
There should now be a Treatment Factors column in the Observation Dataset (with data)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2023-09-22 00:17 UTC, timparsons requested changes

2023-09-22 00:17 UTC, timparsons commented on src/views/import/Dataset.vue
> +      }
While treatment factors are stored for persistence to the brapi storage server, they are translated back to being in `unit.treatments` in `ObservationUnitDAO.java`.  This code should reference that location in the ObservationUnit object rather than in `additionalInfo`

2023-09-28 21:13 UTC, davedrp commented on src/views/import/Dataset.vue
> +      }
done!

2023-09-29 17:07 UTC, timparsons requested changes

2023-09-29 20:04 UTC, davedrp commented on package.json
> +  "version": "v0.9.0+589",
Done

2023-09-29 20:06 UTC, davedrp commented on src/breeding-insight/model/ObservationUnit.ts
> +  treatments?: string[];
Thanks.  Changed.
Upon review of BrAPI, 'any' is the preferred type.

2023-09-29 20:23 UTC, timparsons approved these changes

2023-10-03 15:31 UTC, davedrp commented
Re-opening because it "Closed with unmerged commits"

2023-10-03 17:30 UTC, merged