[BI-1799] - Updated Germplasm Import Preview Pagination
Breeding-Insight/bi-web pull request #335
Opened 2023-09-28 18:36 UTC by mlm483

# Description
**Story:** [Please include a link to the story in Jira](https://breedinginsight.atlassian.net/browse/BI-1799)

- Made the default page size 200.
- Removed the show all button.

# Dependencies
_Please include any dependencies to other code branches, testing configurations, scripts to be run, etc._

# Testing
Upload a Germplasm file and ensure the preview table has a default page size of 200 and there is no show all button.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2023-09-29 20:31 UTC, timparsons requested changes
When testing, initial display looks good.  When I changed the page size from the initial 200 to 20, pagination did not update, and stayed at 200 and on the second page.  Here's my test file for reference:

[1799_bi_germplasm_import_template_v8.xls](https://github.com/Breeding-Insight/bi-web/files/12771517/1799_bi_germplasm_import_template_v8.xls)

2023-10-02 13:36 UTC, dmeidlin approved these changes
Approved assuming the issue Tim found is fixed.

2023-10-02 15:09 UTC, mlm483 commented
> When testing, initial display looks good. When I changed the page size from the initial 200 to 20, pagination did not update, and stayed at 200 and on the second page. Here's my test file for reference:
> 
> [1799_bi_germplasm_import_template_v8.xls](https://github.com/Breeding-Insight/bi-web/files/12771517/1799_bi_germplasm_import_template_v8.xls)

Thanks, `pageSize` was continually being set to 200. I used a different approach, I think it's much cleaner and all 3 upload types appear to have the desired preview behavior.

2023-10-05 18:50 UTC, timparsons approved these changes

2023-10-05 18:55 UTC, merged