BI-1911 fix QA findings
Breeding-Insight/bi-web pull request #341
Opened 2023-10-20 16:09 UTC by davedrp

# Description
[BI-1911](https://breedinginsight.atlassian.net/browse/BI-1911) - in response to Shahana's [testing notes.](https://breedinginsight.atlassian.net/browse/BI-1911?focusedCommentId=14057)

# Dependencies
bi-api: bug/BI-1911-2 branch

# Testing
- Import an Experiment.
- Look at the confirmation page.

**Expected Results**
- The `Env Year`, `Env`, and  `Exp unit ID` columns should appear as they did in the import file.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [x] I have run TAF: _\<link to TAF run>_

[BI-1911]: https://breedinginsight.atlassian.net/browse/BI-1911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-10-20 19:33 UTC, mlm483 requested changes
Functionality looks good, I would strip the program key in bi-api.

2023-10-20 19:33 UTC, mlm483 commented on src/views/import/ImportExperiment.vue
> +  }
I agree, we have static `Utilities` methods to remove program keys in bi-api. If it's not too much effort, I would make the change now.

2023-10-30 13:40 UTC, davedrp commented on src/views/import/ImportExperiment.vue
> +  }
A new story for this ([BI-1973](https://breedinginsight.atlassian.net/browse/BI-1973)) has been written.

2023-10-30 13:48 UTC, mlm483 approved these changes

2023-10-30 15:04 UTC, merged