[BI-2017] Change Germplasm Upload to unify with sample submission
Breeding-Insight/bi-web pull request #367
Opened 2024-03-20 14:23 UTC by davedrp

# Description
[BI-2017] Change Germplasm Upload to unify with sample submission 

Change Germplasm Template column from "Name" to "Germplasm Name"

# Dependencies
bi-api: feature/BI-2017 branch 

# Testing

1. Download Germplasm Import Template.
2. Use Template format to import Germplasm.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2024-03-27 14:53 UTC, nickpalladino requested changes
I think we also need a db migration to change the column name on the import template, whoops missed the backend PR

2024-03-27 14:56 UTC, nickpalladino approved these changes

2024-04-03 16:19 UTC, dmeidlin requested changes
The name changes appear in the germplasm table and import template. When I import
[bi_germplasm_import_template_v9.xls](https://github.com/Breeding-Insight/bi-web/files/14855258/bi_germplasm_import_template_v9.xls) there's a runtime error that crashes bi-api:
`ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: it/unimi/dsi/fastutil/ints/IntIterable
java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/ints/IntIterable
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:642)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.breedinginsight.utilities.FileUtil.parseTableFromJson(FileUtil.java:195)
	at org.breedinginsight.brapi.v2.dao.impl.ImportMappingDAOImpl.parseBrAPIImportMapping(ImportMappingDAOImpl.java:134)
	at org.breedinginsight.brapi.v2.dao.impl.ImportMappingDAOImpl.getSystemMappingByName(ImportMappingDAOImpl.java:124)
	at org.breedinginsight.brapps.importer.services.FileImportService.getSystemMappingByName(FileImportService.java:559)
	at org.breedinginsight.brapps.importer.controllers.ImportController.getSystemMappings(ImportController.java:200)
	at org.breedinginsight.brapps.importer.controllers.$ImportControllerDefinition$$exec6.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:151)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:482)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:121)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.emitRouteResponse(RoutingInBoundHandler.java:1502)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.access$2100(RoutingInBoundHandler.java:151)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$6$1.request(RoutingInBoundHandler.java:1469)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapInnerSubscriber.onSubscribe(FlowableSwitchMap.java:379)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$6.doSubscribe(RoutingInBoundHandler.java:1457)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$6.lambda$subscribe$0(RoutingInBoundHandler.java:1451)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.ints.IntIterable
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)`

2024-04-04 16:57 UTC, dmeidlin approved these changes

2024-04-09 20:39 UTC, mlm483 commented
@davedrp could you please merge this feature branch into `release/0.9` instead of `develop`? We have time to get this and BI-1680 into v0.9, and this PR needs to be merged before BI-1680.

2024-04-10 17:34 UTC, closed without merging