BI-2059 - Field Book not displaying nominal categories from DeltaBreed
Breeding-Insight/bi-web pull request #371
Opened 2024-04-02 17:37 UTC by nickpalladino

# Description
**Story:** [BI-2059](https://breedinginsight.atlassian.net/browse/BI-2059?atlOrigin=eyJpIjoiZThkMWQ5NGJhMWJjNDE5OGI1YmRlODdhYTRhMWUxYmMiLCJwIjoiaiJ9)

- Changed default Field Book BrAPI category settings from Label to Value

# Dependencies
- bi-api release/0.9
- Field Book 

# Testing
- Scan QR code for BrAPI settings in Delta Breed and verify that the category option is set to Value in Field Book
- Verify that both nominal and ordinal traits have values displayed on buttons on collect screen in Field Book

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

[BI-2059]: https://breedinginsight.atlassian.net/browse/BI-2059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-04-03 19:12 UTC, dmeidlin requested changes
I'm running FB v5.6.13 in Android Studio and get this error 
![BI-2059ScanErr](https://github.com/Breeding-Insight/bi-web/assets/14339308/9f5d273a-8966-45ae-9100-c64593c1e90e)
when I scan this QR code 
![FBScanTestBI-2059](https://github.com/Breeding-Insight/bi-web/assets/14339308/5ba3ff02-99f2-426d-82dd-213feecb014a)
. The Value category appears in the Deltabreed UI.

2024-04-03 19:35 UTC, mlm483 approved these changes
Approved, assuming Dave's issue is resolved.

2024-04-05 15:48 UTC, dmeidlin commented
When I try scanning the QR code for the Field-Book demo program on rel-test, I get a different error.
![relTEstFBSyncErr](https://github.com/Breeding-Insight/bi-web/assets/14339308/56b1b156-4965-4b93-9027-cc3e45de0883)

2024-04-05 17:21 UTC, dmeidlin approved these changes

2024-04-05 18:27 UTC, merged