[BI-2102] Accessibility: Make Color Contrast Meet AA Standard
Breeding-Insight/bi-web pull request #384
Opened 2024-06-06 14:48 UTC by davedrp

# Description
[BI-2102](https://breedinginsight.atlassian.net/browse/BI-2102) Accessibility: Make Color Contrast Meet AA Standard

# Dependencies
bi-api: develop branch

# Testing
NOTE: To test this install the Siteimprove Accessibility Checker browser plugin found at https://chromewebstore.google.com/detail/siteimprove-accessibility/djcglbmbegflehmbfleechkjhmedcopn?pli=1

**Go to _BrAPI Information_ page.**
EXPECTED RESULT
The Siteimprove Accessibility Checker should not report the issue `Color contrast does not meet minimum requirement`

 **Go to the _Jobs_ page.**
 EXPECTED RESULT
 The Siteimprove Accessibility Checker should not report the issue `Color contrast does not meet minimum requirement`

 **Go to any page that includes a buefy table with pagination (for example, the _Gemplasm_ page).**
 EXPECTED RESULT
 The Siteimprove Accessibility Checker should not report the issue `Color contrast does not meet minimum requirement`

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

[BI-2102]: https://breedinginsight.atlassian.net/browse/BI-2102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-07 12:25 UTC, dmeidlin approved these changes

2024-06-25 17:23 UTC, mlm483 requested changes

2024-06-25 17:23 UTC, mlm483 commented on src/assets/scss/main.scss
> +//$dark-turquoise: #2d8082;
Please remove or document why this commented-out line is here.

2024-06-25 17:23 UTC, mlm483 commented on src/assets/scss/main.scss.bak
> +/*!
I don't think this file should be in git. If we really need to find the old values, we can look at the commit history.

2024-07-11 19:40 UTC, davedrp commented on src/assets/scss/main.scss
> +//$dark-turquoise: #2d8082;
done

2024-07-11 19:40 UTC, davedrp commented on src/assets/scss/main.scss.bak
> +/*!
done

2024-07-11 19:54 UTC, mlm483 approved these changes
🚀

2024-07-12 13:53 UTC, dmeidlin approved these changes

2024-07-12 15:41 UTC, merged