BI-1693 Add Collaborator To And Remove From Experiment (UI)
Breeding-Insight/bi-web pull request #393
Opened 2024-08-20 19:44 UTC by dmeidlin

# Description
**Story:** [BI-1693](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-1693)

This update introduces functionality to add and remove experimental collaborators in the ExperimentDetails.vue component. Two new modals, `<ExperimentAddCollaboratorModal>` and `<ExperimentCollaboratorRemovalModal>`, are implemented to handle collaborator management. The experiment action menu now includes an option to add collaborators. Additional methods and fields were added to manage collaborator states and retrieve data from the backend. In the UI, a list of assigned collaborators is displayed with options to revoke access. Supporting changes include new SCSS classes and backend service methods in `ExperimentService.ts` and `ExperimentDAO.ts` for managing collaborator data. New model and service layers were also introduced to handle collaborator data retrieval and operations.

# Dependencies
BI-2256, BI-2255 for bi-api

# Testing
   1.  Add Experimental Collaborator to experiment(s)
   2. Remove experimental collaborator from my experiment(s)

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have create/modified unit tests to cover this change
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_

2024-08-22 19:59 UTC, HMS17 commented on src/components/experiments/ExperimentAddCollaboratorModal.vue
> +      <p>An experimental collaborator will  be granted read, dowload, and BrAPI pull access to this experiment ${experiment-name}. If the collaborator is not available from the dropdown menu, they wi
typo, dowload instead of download

2024-08-22 22:06 UTC, HMS17 requested changes

2024-08-22 22:06 UTC, HMS17 commented on src/breeding-insight/model/Collaborator.ts
> +        this.id = id;
What is id meant to be in this case? If it is the id of the ExperimentProgramUserRoleEntity, it will be null for any case where active=false since those users are not yet added as collaborators to that experiment, which I suspect will be a problem for all the downstream logic using collaborator.id

The current ExperimentalCollaboratorResponse object from the backend passes collaboratorId, active, userId, name, and email.

2024-08-26 18:48 UTC, dmeidlin commented on src/breeding-insight/model/Collaborator.ts
> +        this.id = id;
Collaborator.id is used for collaboratorId. I renamed the field to collaboratorId to match the backend. The feature, however, works fine as is. The DELETE collaborators endpoint uses the collaboratorId and there are try-catch blocks for catching any handling any errors. Unless there is a specific problem to be addressed, I'll consider this issue resolved.

2024-08-26 18:48 UTC, dmeidlin commented on src/components/experiments/ExperimentAddCollaboratorModal.vue
> +      <p>An experimental collaborator will  be granted read, dowload, and BrAPI pull access to this experiment ${experiment-name}. If the collaborator is not available from the dropdown menu, they wi
thanks, fixed.

2024-08-26 20:56 UTC, HMS17 commented on src/breeding-insight/model/Collaborator.ts
> +        this.id = id;
Good to know and thanks for the rename. My main concern was the GET endpoint retrieving and displaying a list of collaborators not yet added to the experiment, since the collaboratorId will be null in that case.

2024-08-27 19:34 UTC, HMS17 approved these changes

2024-08-28 13:31 UTC, merged