Bug/bi 72
Breeding-Insight/bi-web pull request #42
Opened 2020-09-10 17:05 UTC by ctucker3

2020-09-14 13:54 UTC, nickpalladino reviewed
Should probably capture requirements somewhere for the changes here because it goes beyond what was specified in the issue. I'll defer to @DebWeigand on where makes the most sense.

2020-09-16 20:13 UTC, DebWeigand requested changes
As per our discussion, I think it would be helpful to have the original message, as shown in the the Jira card BI-72 https://breedinginsight.atlassian.net/browse/BI-72, but highlighted in yellow as a warning "User created, but could not assign orcid. Orcid already in use.", with the form closed.

2020-09-18 15:48 UTC, ctucker3 commented
> As per our discussion, I think it would be helpful to have the original message, as shown in the the Jira card BI-72 https://breedinginsight.atlassian.net/browse/BI-72, but highlighted in yellow as a warning "User created, but could not assign orcid. Orcid already in use.", with the form closed.

Pushed up changes. @DebWeigand to Nick's comment, do you have thoughts where to update requirements for the extra orcid duplicate check and the invalid orcid check?

2020-09-18 16:01 UTC, nickpalladino approved these changes
Approved assuming you and Deb will capture the requirements.

2020-09-22 04:29 UTC, dmeidlin approved these changes

2020-09-22 18:14 UTC, DebWeigand approved these changes

2020-09-22 19:11 UTC, merged