BI-2373 Add Delete Option to Germplasm Lists View
Breeding-Insight/bi-web pull request #420
Opened 2024-12-10 19:36 UTC by dmeidlin

# Description
**Story:** [BI-2373](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-2373)

# Dependencies
[BI-2372](https://github.com/Breeding-Insight/bi-api/pull/434) [BI-2374](https://github.com/Breeding-Insight/brapi-Java-TestServer/pull/38)

# Testing

- Import a germplasm list to a project
- navigate to the project's germplasm lists table and click on the details link for the imported list
- in the list details table click on manage-list and select delete
- verify that the list no longer appears in the lists table
- navigate to the all-germplasm tab and verify that the individual germplasm contained in the deleted list are still present

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have tested my code and ensured it meets the acceptance criteria of the story
- [] I have create/modified unit tests to cover this change
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation
- [ ] I have run TAF: _\<link to TAF run>_
- [ ] I have run SiteImprove on pages impacted by changes

2024-12-11 17:36 UTC, HMS17 requested changes
A couple comments

2024-12-18 16:05 UTC, dmeidlin commented on src/components/germplasm/GermplasmListDeletionlModal.vue
> +    modal-class="experiment-observation-remove-collaborator-button"
Yep, I added the germplasm-list-deletion-button class.

2024-12-18 16:05 UTC, dmeidlin commented on src/components/germplasm/GermplasmListDeletionlModal.vue
> +export default class ExperimentCollaboratorRemovalModal extends Vue {
Yep! I made the change.

2024-12-18 18:26 UTC, HMS17 approved these changes

2024-12-18 20:18 UTC, mlm483 requested changes
In addition to my comments, one thing to consider is making the list name a link to the list detail view rather than having a separate "Details" action stacked on top of "Download". I think it would make the UI easier to navigate.

2024-12-18 20:18 UTC, mlm483 commented on src/breeding-insight/service/ListService.ts
> +
I did some testing and I don't think this is necessary. Could you remove it, or, if it's necessary, document why?

```suggestion
```

2024-12-19 21:52 UTC, dmeidlin commented on src/breeding-insight/service/ListService.ts
> +                params: { hardDelete: true }
> What's the point of having that hardDelete option if the value is hard-coded?

All BrAPI DELETE endpoints, for consistency, have the same parameters. The DeltaBreed backend, therefore, also has a hardDelete parameter for DELETE /lists, even though Deltabreed lists are always hard-deleted.

> Could hardDelete be a parameter with a default value?

Since lists are always hard-deleted, I don't see the benefit of adding a parameter or a default value. It just moves the hard-coding up a layer and opens up the possibility of a developer or user interaction inadvertently not setting the param or setting it to the wrong value.

2024-12-19 22:01 UTC, dmeidlin commented on src/views/germplasm/GermplasmByList.vue
>      </h1>
The edit on line 26 just fixes the old filter syntax that was throwing an error. The filter has the same functionality and list names are displayed with case sensitivity, so I don't think there is any change needed here.

2024-12-19 22:12 UTC, dmeidlin commented on src/breeding-insight/service/ListService.ts
> +
Yep, I've updated the comment to read:

>  Check if the error is actually a 204 No Content response since http clients can be configured to automatically throw an error if the response has no content

2024-12-19 22:22 UTC, dmeidlin commented
> In addition to my comments, one thing to consider is making the list name a link to the list detail view rather than having a separate "Details" action stacked on top of "Download". I think it would make the UI easier to navigate.

That's a valid point. I would bring this up at a meeting and at least let @shawnyarnes weigh in since it's a UI change, rather than tacking it on to this feature where the scope doesn't really overlap.

2024-12-20 13:38 UTC, mlm483 commented on src/breeding-insight/service/ListService.ts
> +                params: { hardDelete: true }
That's reasonable, thanks for the explanation.

2024-12-20 13:40 UTC, mlm483 commented on src/breeding-insight/service/ListService.ts
> +
I see, so it's not a currently used code path, but more defensive coding?

2024-12-20 14:05 UTC, mlm483 commented on src/views/germplasm/GermplasmByList.vue
>      </h1>
My initial comment may have been unclear, I'm talking about the `<h1>` on the germplasm by list view. In this screenshot, you can see how the list of lists view shows the case-sensitive names, but the germplasm by list view uses `toStartCase`. I recommend removing the call to `toStartCase` on line 26 of GermplasmByList.vue.
![Screenshot 2024-12-20 at 9 01 37 AM](https://github.com/user-attachments/assets/47fccd82-d858-4177-ad08-3784472127cd)

2024-12-20 15:26 UTC, dmeidlin commented on src/views/germplasm/GermplasmByList.vue
>      </h1>
Agreed. I removed the filter.

2024-12-20 16:00 UTC, mlm483 approved these changes

2025-01-10 20:57 UTC, merged