[BI-626] Handle login error and logout user before starting login process
Breeding-Insight/bi-web pull request #50
Opened 2020-10-19 20:35 UTC by ctucker3

Fixes issue with the nonce token (a token in the openid handshake that identifies a request upon return to open id requestor) expiring during the login process. The token still expires, but a bad token validation is handled and the user is notified on the front page to try again. I increase the expiration time to 10 minutes (it was 5 minutes). 

I also included a way to log out of open id before beginning the login process. This should be able to handle any Open ID provider if they have a logout URI. The logout url isn't required, and the process skips over that part if the logout attempt fails, or if the url isn't provided in the config. 

# Dependent PRs
https://github.com/Breeding-Insight/bi-api/pull/51

# Testing

1. Try changing the cookie expiration to 1s and check that you get the right page (see below)
2. Try logging in with an OrcID without a BI account, make sure you still get the right not authorized page. Make sure you can log into a good OrcID account after that. 
3. Try logging into an OrcID account, then log out, and then try logging in again. Make sure the orcid page pops up. 

# The way things should look

Here is the message the user gets when the authentication has timed out. 

![screencapture-localhost-8080-2020-10-19-15_28_55](https://user-images.githubusercontent.com/17887341/96508306-65bfea00-1228-11eb-96c1-8454631e6143.png)

Here is a loading wheel I added to the OrcID button after you click it. I added this because we now have two calls in the login process, a BI backend health check and an orcid logout. If they take a few beats it lets the user know we are doing stuff. 
![screencapture-localhost-8080-401-2020-10-19-16_33_04](https://user-images.githubusercontent.com/17887341/96508554-c6e7bd80-1228-11eb-86de-006ac6a6db32.png)

Unchanged is our not authorized screen.  
![screencapture-localhost-8080-2020-10-19-15_27_48](https://user-images.githubusercontent.com/17887341/96508364-7a03e700-1228-11eb-83d8-8b88b444329a.png)

2020-10-19 21:29 UTC, timparsons requested changes
Looks good!  Have one requested change for blocking additional clicks on the login button while it's in the loading mode.

2020-10-19 21:29 UTC, timparsons commented on src/views/Index.vue
> +          v-on:click="orcidLogin"
Can the button also be disabled when clicked to prevent multiple clicks by a user?

2020-10-19 21:29 UTC, timparsons commented on src/views/Index.vue
> +    async orcidLogin() {
I assume this had to be changed to be asychronous because it would block and not allow the login button to show the spinner?

2020-10-20 13:05 UTC, eawoods commented
Looked over design and workflow changes by request. The loading indicator is slick, nicely applied! All looks beautiful.

2020-10-20 13:32 UTC, ctucker3 commented on src/views/Index.vue
> +    async orcidLogin() {
This is async now since I used `await` inside the method for the api calls instead of `.then().catch()`. It doesn't seem to effect Vue at all.

2020-10-20 13:41 UTC, ctucker3 commented on src/views/Index.vue
> +          v-on:click="orcidLogin"
Yep! Removed the `disabled` class, and added a `disabled` conditional attribute.

2020-10-20 14:11 UTC, timparsons approved these changes

2020-10-20 15:56 UTC, nickpalladino commented on src/breeding-insight/dao/UserDAO.ts
> +    return api.call({url: logoutUrl, method: 'get'});
Are there any issues with doing this as an API call? I just remember one time we were doing something login/logout related as an api call rather than a browser redirect and it was causing us issues. Just wanted to make sure we don't run into that issue.

2020-10-20 16:03 UTC, ctucker3 commented on src/breeding-insight/dao/UserDAO.ts
> +    return api.call({url: logoutUrl, method: 'get'});
It seems to work fine. This is the way that they recommend it in the orcid documentation as well. 

https://members.orcid.org/api/resources/customize#logout

2020-10-20 16:42 UTC, timparsons commented on src/breeding-insight/dao/UserDAO.ts
> +    return api.call({url: logoutUrl, method: 'get'});
I don't think the API can handle this because the logout function at ORCiD is most likely nuking all the cookies to log you out (as well as whatever they need to do on the backend).  Because of this, it needs to be from the client side (browser), and not from our API.

2020-10-20 17:26 UTC, ctucker3 commented on src/breeding-insight/dao/UserDAO.ts
> +    return api.call({url: logoutUrl, method: 'get'});
Yep, that was my understanding as well, and appears to be the case as I was testing it out during implementation. I played with the idea of adding a redirect to the orcid logout page with an ajax callback function (see link above) for a redirect back to bi-api as part of the backend login flow but this seemed like a more straight forward approach.

2020-10-20 18:55 UTC, nickpalladino approved these changes

2020-10-20 19:00 UTC, merged