[BI-652] - New account signup
Breeding-Insight/bi-web pull request #53
Opened 2020-10-23 17:59 UTC by ctucker3

See bi-api pull request: https://github.com/Breeding-Insight/bi-api/pull/55

2020-11-02 14:45 UTC, eawoods requested changes
I didn't run this locally, but I did carefully review the video.
Some language changes to the dialog boxes and email message are suggested inline, here and in the bi-api repo.

Would it be possible to remove the second step to log in again once the account is activated? Could we just have a button that "completes" the activation by taking them to their account page (authorized-user home page)? If there's a security reason to reauthenticate, I could see having the second login after activating the account, but otherwise let's make it simpler and just send the new user to their account, replacing the "Return to home page" link on the activation page with some new language and a direct link. Thoughts?

2020-11-02 14:45 UTC, eawoods commented on src/views/AccountCreationFailure.vue
> +                    OrcID is already linked to a different account
ORCID iD

2020-11-02 14:45 UTC, eawoods commented on src/views/AccountCreationFailure.vue
> +                    OrcID is already linked to a different account
The title of this error message confused me -- after talking this over with Chris, could this maybe be more accurate as "A Breeding Insight user with this ORCID iD already exists." and supporting text to help solve the problem:  "Check that the email account used for signup is the same as your ORCID iD, and check with your programs to confirm that you do not have an account under another email address. Contact a system administrator if the problem persists." Or something similar.  We talked about how this problem is likely to occur only for us/developers, but it's good to have a clear description of what's going on just in case this ever does get displayed out in the wild.

2020-11-02 14:45 UTC, eawoods commented on src/views/AccountCreationSuccess.vue
> +            <router-link v-bind:to="{name:'home'}" v-bind:replace="true">
Styled as button: "Go to my account"

2020-11-02 14:45 UTC, eawoods commented on src/views/AccountCreationSuccess.vue
> +              Your account has been successfully activated. To log in, return to the home page
Suggested:
"Your account has been successfully activated. Visit your account page to get started!"

2020-11-02 16:07 UTC, ctucker3 commented on src/views/AccountCreationFailure.vue
> +                    OrcID is already linked to a different account
Proposal for supporting text:

```
Check with your program to confirm that you do not have an account under another email address. Contact a system administrator if the problem persists.
```

The email account on the BI account does not need to be the same as the orcid email. 

Thoughts, @eawoods ?

2020-11-02 16:17 UTC, ctucker3 commented on src/views/AccountSignUp.vue
> +          alongside your name in our application. Learn more in
Good point, no we don't do that. I copied this text from the home page login modal, so this looks like a pre-existing issue. I would say we should make a new card for this since it was an existing issue.

2020-11-02 16:28 UTC, ctucker3 commented on src/views/AccountCreationFailure.vue
> +                    OrcID is already linked to a different account
Changed and pushed, the user doesn't have to relogin now. See screen shot below:

![screencapture-localhost-8080-account-success-2020-11-02-11_24_59](https://user-images.githubusercontent.com/17887341/97892791-75e2c980-1cfe-11eb-959e-96431892d575.png)

2020-11-02 16:28 UTC, ctucker3 commented on src/views/AccountCreationSuccess.vue
> +            <router-link v-bind:to="{name:'home'}" v-bind:replace="true">
Changed and pushed, see comment thread above.

2020-11-02 16:28 UTC, ctucker3 commented on src/views/AccountCreationSuccess.vue
> +              Your account has been successfully activated. To log in, return to the home page
Changed and pushed

2020-11-02 16:29 UTC, ctucker3 commented
> I didn't run this locally, but I did carefully review the video.
> Some language changes to the dialog boxes and email message are suggested inline, here and in the bi-api repo.
> 
> Would it be possible to remove the second step to log in again once the account is activated? Could we just have a button that "completes" the activation by taking them to their account page (authorized-user home page)? If there's a security reason to reauthenticate, I could see having the second login after activating the account, but otherwise let's make it simpler and just send the new user to their account, replacing the "Return to home page" link on the activation page with some new language and a direct link. Thoughts?

![screencapture-localhost-8080-account-error-2020-11-02-11_29_15](https://user-images.githubusercontent.com/17887341/97892936-aaef1c00-1cfe-11eb-8791-cddc310e96b3.png)

2020-11-02 18:42 UTC, eawoods commented on src/views/AccountCreationFailure.vue
> +                    OrcID is already linked to a different account
Love it!!!! And yes on the supporting text for error message.

2020-11-02 18:43 UTC, eawoods approved these changes
Looking good!

2020-11-02 23:10 UTC, timparsons requested changes

2020-11-02 23:10 UTC, timparsons commented on src/components/program/ProgramUsersTable.vue
> +      this.newUser = this.checkExistingUserByEmail(this.newUser, this.systemUsers);
I don't think this should happen on the UI, especially because there is logic on the backend to check for any existing user with the same email, and the 409 - CONFLICT status code is returned if so.

2020-11-04 14:44 UTC, nickpalladino approved these changes

2020-11-04 16:45 UTC, ctucker3 commented on src/views/AccountSignUp.vue
> +          alongside your name in our application. Learn more in
Created a card for this:

https://breedinginsight.atlassian.net/browse/BI-666

2020-11-04 16:47 UTC, ctucker3 commented on src/components/program/ProgramUsersTable.vue
> +      this.newUser = this.checkExistingUserByEmail(this.newUser, this.systemUsers);
This is a previous feature, the changes here are just to remove the orcid check. Thoughts on me creating a new card for this to add this email check to the backend?

2020-11-04 17:54 UTC, timparsons commented on src/components/program/ProgramUsersTable.vue
> +      this.newUser = this.checkExistingUserByEmail(this.newUser, this.systemUsers);
Ah ok, I thought that method was added just for the ORCiD input.  I’m ok with leaving it as is, and creating a card to move this check to the backend.

2020-11-04 17:57 UTC, timparsons approved these changes

2020-11-04 18:01 UTC, ctucker3 commented on src/components/program/ProgramUsersTable.vue
> +      this.newUser = this.checkExistingUserByEmail(this.newUser, this.systemUsers);
After talking with Tim. This method will be a stand in until we can get the user search implemented. Also adding a card in to make some changes to the backend:

https://breedinginsight.atlassian.net/browse/BI-667

2020-11-04 20:41 UTC, timparsons approved these changes

2020-11-09 14:21 UTC, merged