[BI-85] - Create new trait UI
Breeding-Insight/bi-web pull request #58
Opened 2020-11-30 16:32 UTC by ctucker3

Adds the ability to create a basic trait from the UI. 

Error display is not implemented yet, so you will get a generic error when trait creation fails. Open the developer console to see the errors printed out. You might need the console open before submitting for the errors to be printed. 

Some scale classes may fail because the specific scale additionals aren't in there yet. You will get errors like "Missing categories for scale class 'Categories'" or something along those lines.

2020-12-01 21:54 UTC, nickpalladino requested changes
Form looks good, on mobile too.

2020-12-01 22:00 UTC, nickpalladino requested changes

2020-12-01 22:00 UTC, nickpalladino commented on src/components/trait/forms/BaseTraitForm.vue
> +  filteredDataObj(data: string[]): string[] {
May be a nice to have but this seems to match any letter in the observation level rather than a sequence starting with the first letter.

2020-12-02 15:13 UTC, ctucker3 commented on src/breeding-insight/service/TraitService.ts
> +            biResponse.result.data = PaginationController.mockSortRecords(biResponse.result.data);
I think this is needed for now to show the new trait at the top when it is added from the new trait from. Otherwise, it could appear on a different page and the user wouldn't see it.

2020-12-02 15:19 UTC, ctucker3 commented on src/components/trait/forms/BaseTraitForm.vue
> +  filteredDataObj(data: string[]): string[] {
Yeah it should match any substring with the options. So if typed, `lo` that should match `Plot` and `Lot' and 'Slot' and.... well I'll stop showing off my rhyming skills! When I'm on the interwebs, I usually like search bars like this instead of stricter search bars that search from the beginning.

2020-12-02 15:29 UTC, ctucker3 commented on src/breeding-insight/dao/ProgramDAO.ts
> +      url: `${process.env.VUE_APP_BI_API_V1_PATH}/programs/${programId}/observation_level`,
Yep, good catch. Changed and pushed.

2020-12-02 16:43 UTC, nickpalladino commented on src/breeding-insight/service/TraitService.ts
> +            biResponse.result.data = PaginationController.mockSortRecords(biResponse.result.data);
Ah ya, that's right. Now you can do that on this page.

2020-12-02 16:44 UTC, nickpalladino commented on src/components/trait/forms/BaseTraitForm.vue
> +  filteredDataObj(data: string[]): string[] {
ok, works for me.

2020-12-02 18:34 UTC, nickpalladino requested changes

2020-12-02 18:34 UTC, nickpalladino commented on src/breeding-insight/dao/ProgramDAO.ts
> +      url: `${process.env.VUE_APP_BI_API_V1_PATH}/programs/${programId}/observation-level`,
can you add an 's' making it observation-levels

2020-12-02 18:34 UTC, nickpalladino commented on src/breeding-insight/model/Scale.ts
> -  Code = "CODE",
This is used in TraitDetailPanel, granted it's not really doing anything with it at this point.

2020-12-02 21:59 UTC, timparsons requested changes
Looks great!!  I did have a couple of things:

1.  I accidentally ran into an issue where I clicked "Save" twice before the form closed (for whatever reason the app was being slow the first time I tried saving), and the trait table was updated.  After the table was updated, I had two records with duplicate information.  I verified this again, and was indeed able to create identical traits by double clicking the "Save" button.  @ctucker3 and I talked about this, and agreed that it would be best to disable the "Save" button after it's clicked to prevent double clicking, AND to add database constraints to check for uniqueness in the case that two identical trait POST requests are made simultaneously.

2. For the observation level input, I noticed that the autocomplete values are visible when focus is put on the input.  It wasn't obvious to me that a new observation level could be made by typing it into the input.  @eawoods could messaging be added to the input (or maybe even in the autocomplete box), and what should that look like?

2020-12-02 21:59 UTC, timparsons commented on src/components/trait/TraitListsTable.vue
> +  private scaleClassOptions: string[] = Object.values(DataType);
Would it be possible to change the method and scale classes to be arrays of `option` -> `{id: <enum value>, name: <enum but with only first letter capitalized>}`?

2020-12-02 22:00 UTC, ctucker3 commented on src/breeding-insight/dao/ProgramDAO.ts
> +      url: `${process.env.VUE_APP_BI_API_V1_PATH}/programs/${programId}/observation-level`,
changed and pushed

2020-12-03 17:59 UTC, eawoods commented
> 2. For the observation level input, I noticed that the autocomplete values are visible when focus is put on the input.  It wasn't obvious to me that a new observation level could be made by typing it into the input.  @eawoods could messaging be added to the input (or maybe even in the autocomplete box), and what should that look like?

How about having placeholder text in the field that says "Start typing to see suggestions" ?

2020-12-03 19:19 UTC, ctucker3 commented on src/components/trait/TraitListsTable.vue
> +  private scaleClassOptions: string[] = Object.values(DataType);
changed and pushed

2020-12-03 19:19 UTC, ctucker3 commented on src/breeding-insight/model/Scale.ts
> -  Code = "CODE",
removed

2020-12-04 16:26 UTC, ctucker3 commented
> Looks great!! I did have a couple of things:
> 
> 1. I accidentally ran into an issue where I clicked "Save" twice before the form closed (for whatever reason the app was being slow the first time I tried saving), and the trait table was updated.  After the table was updated, I had two records with duplicate information.  I verified this again, and was indeed able to create identical traits by double clicking the "Save" button.  @ctucker3 and I talked about this, and agreed that it would be best to disable the "Save" button after it's clicked to prevent double clicking, AND to add database constraints to check for uniqueness in the case that two identical trait POST requests are made simultaneously.

My database constraints didn't work with the double click, although they would work with a regular query. I'm thinking those queries are being executed simultaneously so the duplicates aren't being caught. I created a new card to look into this:

https://breedinginsight.atlassian.net/browse/BI-689

The prevention of the double click on the UI is implemented for traits. It needs to be added to the other forms still though. 

> 2. For the observation level input, I noticed that the autocomplete values are visible when focus is put on the input.  It wasn't obvious to me that a new observation level could be made by typing it into the input.  @eawoods could messaging be added to the input (or maybe even in the autocomplete box), and what should that look like?

Implemented Liz's suggestion of the placeholder.

2020-12-04 17:21 UTC, timparsons approved these changes

2020-12-07 15:58 UTC, nickpalladino approved these changes

2020-12-07 16:41 UTC, merged