[BI-671] - Create new trait - Scale class 'ordinal scale'
Breeding-Insight/bi-web pull request #60
Opened 2020-12-02 20:48 UTC by ctucker3

2020-12-07 17:52 UTC, timparsons requested changes

2020-12-07 17:52 UTC, timparsons commented on src/components/trait/forms/BaseTraitForm.vue
> +        />
This element and `Ordinal` could be combined.  The `type` passed to `CategoryTraitForm` can be the value of `trait.scale.dataType`

2020-12-08 18:32 UTC, nickpalladino approved these changes

2020-12-08 18:32 UTC, nickpalladino commented on src/components/trait/forms/BaseTraitForm.vue
> +      <template v-if="trait.scale && trait.scale.dataType === DataType.Text">
There's also a method to do a case insensitive comparison for the DataType in the Scale class. Not important here since it's a new trait but may be for edit where that info could possibly come in differently.

2020-12-08 19:26 UTC, ctucker3 commented on src/components/trait/forms/BaseTraitForm.vue
> +      <template v-if="trait.scale && trait.scale.dataType === DataType.Text">
Ok, that might be good to check. I was thinking that those data types got transformed into the enum values which is why I didn't worry about case matching. I'll leave that for the edit form card if that is cool with you?

2020-12-08 19:27 UTC, ctucker3 commented on src/components/trait/forms/BaseTraitForm.vue
> +        />
Good catch. This is changed in one of the next PR's I have open.

2020-12-09 15:22 UTC, timparsons approved these changes

2020-12-09 15:25 UTC, merged