[BI-685] - Map backend trait validation errors to front end
Breeding-Insight/bi-web pull request #63
Opened 2020-12-14 16:31 UTC by ctucker3

2020-12-15 14:35 UTC, timparsons requested changes

2020-12-15 14:45 UTC, ctucker3 commented on src/breeding-insight/model/errors/ValidationError.ts
> +            errorSentence += `${field.field}: ${field.errorMessage}; `;
That's a good point, I can remove the fields for the error sentence. The other fields don't have the error sentence yet, but I think they can just use the errorMessage as well since we will have to custom create those sentences from the UI validation.

2020-12-15 14:54 UTC, ctucker3 commented on src/breeding-insight/model/errors/ValidationError.ts
> +            errorSentence += `${field.field}: ${field.errorMessage}; `;
Changed and pushed

2020-12-15 14:56 UTC, timparsons approved these changes

2020-12-16 16:21 UTC, nickpalladino reviewed
One thing that may be weird for people is the way our front end validations clear prior to submit where the backend ones don't until a re-save is attempted. Maybe we should change how the front end ones work for consistency at some point?

2020-12-16 16:21 UTC, nickpalladino commented on src/components/trait/TraitListsTable.vue
> +        this.$emit('show-error-notification', `Error creating trait. ${this.validationHandler.condenseErrorsSingleRow()}`);
Not exactly a 1-to-1 mapping between error message and UI but probably no getting around that. For example, if you don't change the form from the loading state and try to submit, one of the error messages will be missing scale name which isn't present on the form and would be rectified by selecting a scale class/setting unit.

2020-12-16 16:21 UTC, nickpalladino commented on src/assets/scss/main.scss
> +svg.feather {
Since this is a global change, it affects alignment of icons used elsewhere like the table row chevrons, and possibly other stuff. I preferred the old alignment of chevrons, didn't check everywhere else.

2020-12-21 16:44 UTC, ctucker3 commented on src/components/trait/TraitListsTable.vue
> +        this.$emit('show-error-notification', `Error creating trait. ${this.validationHandler.condenseErrorsSingleRow()}`);
Good catch, I mapped the scale name error for the fields but not for the top notification. I added mappings for those, changes are pushed up. The scale name is the tricky part because it has multiple roles depending on the data type.

2020-12-21 16:45 UTC, ctucker3 commented on src/assets/scss/main.scss
> +svg.feather {
Yeah, I liked the old alignment for the chevrons too. I missed that when checking the icon changes. I changed it back and made appropriately changes to my new warning labels directly.

2020-12-21 19:51 UTC, nickpalladino approved these changes

2021-01-05 15:16 UTC, merged