[BI-563] Archive Individual Trait
Breeding-Insight/bi-web pull request #70
Opened 2021-01-29 17:44 UTC by dmeidlin

The Trait model was updated to include the "active" property and set it to true by default.

The Archiving features in the UI can be activated/deactivated by toggle the state of the archivable prop in TraitsListTable.
Archivable should be set to false until the "active" property is included in trait data from bi-api.

Given: The user has navigated to the "Trait Management" screen
And: the user has selected a trait to view
When: the user clicks "Archive" on the detail pane
Then: ensure that a confirmation dialog appears

Given: The user has clicked “Archive”
When: they confirm archiving the trait
Then: ensure that the trait detail pane is closed
And: ensure that the row shows an indicator that the trait is archived
And: ensure that a success notification is displayed at the top of the screen

Given: The user has clicked “Archive”
When: they decline archiving the trait
Then: ensure that the archive confirmation dialog closes
And: ensure that the trait is not archived

Given: The user has navigated to the "Trait Management" screen
When: the user has selected an archived trait to view
Then: ensure that the ‘Archived’ tag is displayed at the bottom of the detail pane

Given: that there is more than one page of traits in the trait list
When: the user archives a trait that is not on the first page
Then: ensure that the page in view is reset to the first page

2021-02-02 18:44 UTC, ctucker3 approved these changes
Looks good! I didn't run it locally but the code looks good. I had a few questions and comments, but approving since I'll be out the rest of the week.

2021-02-02 18:44 UTC, ctucker3 commented on package.json
> +  "devport": "8082",
Does this need to stay changed or can we change it back to 8080?

2021-02-02 18:44 UTC, ctucker3 commented on src/components/trait/TraitDetailPanel.vue
> +      <template v-if="archivable && !data.active">
Can this just be `!data.active`? The data can be archived without the table providing archiving abilities. One route I can think of is if the status is set to inactive in the import (not sure if we support that yet).

2021-02-02 18:44 UTC, ctucker3 commented on src/components/trait/TraitListsTable.vue
> +            <strong>Yes, {{ focusTrait.active ? 'remove' : 'restore' }}</strong>
Should this be `Yes, archive` instead of `Yes, remove`?

2021-02-02 18:44 UTC, ctucker3 commented on src/components/trait/TraitListsTable.vue
> +      const traitClone = JSON.parse(JSON.stringify(this.focusTrait));
Never knew that was a way to clone! There is also the `Trait.assign` function in the trait object if you want a trait class instance.

2021-02-03 21:11 UTC, nickpalladino commented on package.json
> +  "devport": "8082",
+1

2021-02-03 21:45 UTC, nickpalladino commented on src/components/trait/TraitListsTable.vue
> +          v-bind:archivable="false"
Why is this false? I guess that's why I don't see an archive link in the detail pane?

2021-02-03 21:49 UTC, nickpalladino commented on src/components/trait/TraitListsTable.vue
> +            <strong>Yes, {{ focusTrait.active ? 'remove' : 'restore' }}</strong>
+1

2021-02-03 21:49 UTC, nickpalladino commented on src/components/trait/TraitListsTable.vue
> +      this.deactivateWarningTitle = `Remove "${focusTrait.traitName}" from ${this.activeProgram!.name!}?`;
Similar to previous comment, maybe this should also use archive terminology

2021-02-08 17:33 UTC, dmeidlin commented on package.json
> +  "devport": "8082",
The webserver is running on 8082 because the brapi-server is running on 8080.
There are other PRs related to this pending review:
https://github.com/Breeding-Insight/bi-docker-stack/pull/8,
https://github.com/Breeding-Insight/bi-api/pull/67

2021-02-08 18:11 UTC, dmeidlin commented on src/components/trait/TraitListsTable.vue
> +      const traitClone = JSON.parse(JSON.stringify(this.focusTrait));
Assign would probably work in this case, but I generally stay away from it because it can cause errors if a property of interest is deeply nested (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign).

Also, I remember seeing a comparison of computational effort required for the JSON parsing method for deep cloning versus using methods in underscore or other libraries, and JSON parsing came out on top, so I generally use it for cloning.

2021-02-08 22:19 UTC, dmeidlin commented on src/components/trait/TraitListsTable.vue
> +          v-bind:archivable="false"
Just documenting what we talked about earlier:
The frontend logic works once the "active" trait is returned from the api. Mocking out flagging some traits as archived and others not while preventing the mocks to be overwritten by calls to the trait api was beyond the scope of this work and not really of great value. Without the archivable boolean flag stored per trait the feature can't function properly, so the archivable flag is set to false to turn the feature off until the backend is ready.

2021-02-08 22:50 UTC, dmeidlin commented on src/components/trait/TraitListsTable.vue
> +            <strong>Yes, {{ focusTrait.active ? 'remove' : 'restore' }}</strong>
I used "remove" because it was already in place in the warning modal. The following is from commit ee46948:
`<template>
  <section id="traitTableLabel">
    <WarningModal
      v-bind:active.sync="deactivateActive"
      v-bind:msg-title="'Remove trait from Program name?'"
      v-on:deactivate="deactivateActive = false"
    >
      <section>
        <p class="has-text-dark">
          Program-related data referencing this trait will not be affected by this change.
        </p>
      </section>
      <div class="columns">
        <div class="column is-whole has-text-centered buttons">
          <button v-on:click="modalDeleteHandler()" class="button is-danger"><strong>Yes, remove</strong></button>
          <button v-on:click="deactivateActive = false" class="button">Cancel</button>
        </div>
      </div>              
    </WarningModal>
`
The design reference doesn't show anything for the warning modal, and I think "archive" is more accurate than "remove", so I'm fine with making the change.

2021-02-08 22:52 UTC, dmeidlin commented on src/components/trait/TraitListsTable.vue
> +            <strong>Yes, {{ focusTrait.active ? 'remove' : 'restore' }}</strong>
Sorry the code didn't typeset well; try again...
   <WarningModal
      v-bind:active.sync="deactivateActive"
      v-bind:msg-title="'Remove trait from Program name?'"
      v-on:deactivate="deactivateActive = false"
    >
      <section>
        <p class="has-text-dark">
          Program-related data referencing this trait will not be affected by this change.
        </p>
      </section>
      <div class="columns">
        <div class="column is-whole has-text-centered buttons">
          <button v-on:click="modalDeleteHandler()" class="button is-danger"><strong>Yes, remove</strong></button>
          <button v-on:click="deactivateActive = false" class="button">Cancel</button>
        </div>
      </div>              
    </WarningModal>

2021-02-08 22:55 UTC, dmeidlin commented on src/components/trait/TraitListsTable.vue
> +            <strong>Yes, {{ focusTrait.active ? 'remove' : 'restore' }}</strong>
Ok, this works. Sorry for spamming your inbox. :-)
```
   <WarningModal
      v-bind:active.sync="deactivateActive"
      v-bind:msg-title="'Remove trait from Program name?'"
      v-on:deactivate="deactivateActive = false"
    >
      <section>
        <p class="has-text-dark">
          Program-related data referencing this trait will not be affected by this change.
        </p>
      </section>
      <div class="columns">
        <div class="column is-whole has-text-centered buttons">
          <button v-on:click="modalDeleteHandler()" class="button is-danger"><strong>Yes, remove</strong></button>
          <button v-on:click="deactivateActive = false" class="button">Cancel</button>
        </div>
      </div>              
    </WarningModal>
```

2021-02-08 22:58 UTC, dmeidlin commented on src/components/trait/TraitListsTable.vue
> +      this.deactivateWarningTitle = `Remove "${focusTrait.traitName}" from ${this.activeProgram!.name!}?`;
Agreed.

2021-02-08 23:44 UTC, dmeidlin commented on src/components/trait/TraitDetailPanel.vue
> +      <template v-if="archivable && !data.active">
Yes, the !data.active check is all that is required once the backend returns the active status as part of the trait data.

When the traits are pulled from the backend the trait data is looped over all defined key values when creating the trait objects for the frontend. Since the active property does not appear in the trait data, data.inactive will be undefined and !data.active will be true for all traits even though they are active. So the achivable check is in place to turn these sections off until the backend can support archiving.  Once the backend part is working the archivable check can be removed.

2021-02-09 17:03 UTC, nickpalladino commented on src/components/trait/TraitListsTable.vue
> +          v-bind:archivable="false"
Can we fix bi-api as part of this card so that we can test this feature? It looks like createTraits in TraitService needs to set the active field in the TraitEntity as it's writing null to the database currently.

2021-02-11 16:21 UTC, ctucker3 commented on package.json
> +  "devport": "8082",
The brapi server runs internally in the container as 8080 and externally as 8083, so I think the web could stay as 8080.

2021-02-11 16:24 UTC, ctucker3 commented on src/components/trait/TraitListsTable.vue
> +      const traitClone = JSON.parse(JSON.stringify(this.focusTrait));
That makes sense. Just to clarify, the `Trait.assign` is a custom function of ours that is implemented in our classes.

2021-02-11 20:56 UTC, ctucker3 requested changes
From our discussion during sprint planning. Can we move the `Archive` tag to another column or create a new card to do that?

2021-02-15 13:56 UTC, ctucker3 commented on src/components/trait/TraitListsTable.vue
> +          v-bind:archivable="false"
For traceability, I fixed bi-api in the BI-732 PR that is currently open.

2021-02-17 18:51 UTC, DebWeigand requested changes
This scenario, as is written in the card, does not pass (unless I am misunderstanding)
**Given:** that there is more than one page of traits in the trait list
**When:** the user archives a trait that is not on the first page
**Then:** ensure that the page in view is reset to the first page

after archiving the trait on the second page, the view does not go back to the first page. BUT, do we really want it too?  Don't we want to see it in the list as archived on the original page it was on?  Or, I may be just misunderstanding...

2021-02-19 21:04 UTC, dmeidlin commented on package.json
> +  "devport": "8082",
Ok, will change the port back.

2021-02-19 21:10 UTC, dmeidlin commented
@ctucker3 I think it's fine adding the archive badge as another column in this PR. Now that the backend is working I'll merge in the updates from https://github.com/Breeding-Insight/bi-web/pull/77 and add the change with the extra column.

2021-02-25 13:30 UTC, ctucker3 approved these changes

2021-02-25 20:35 UTC, DebWeigand approved these changes

2021-02-25 22:25 UTC, nickpalladino approved these changes

2021-03-01 16:55 UTC, merged