[BI-698] Import Traits not available until refreshing page after adding self to program
Breeding-Insight/bi-web pull request #76
Opened 2021-02-08 17:46 UTC by dmeidlin

If the active user is being added to a program then the active user roles are updated as part of the success handler.

Description: Import Traits not available until refreshing page after adding self to program
Component/Version: v0.2
Steps to Reproduce

login as admin

add self to a program

select traits in left navigation bar

Expected result:
Import Traits visible as a selection 

Actual Result:
Import traits not visible until the page is refreshed

2021-02-08 22:20 UTC, timparsons approved these changes
Looks good.  Approving contingent on fixing the build error.

2021-02-11 13:59 UTC, ctucker3 approved these changes

2021-02-16 19:45 UTC, DebWeigand requested changes
When I test this, following the exact steps to reproduce, I can pass this.  
But, if I add myself as a 'member' first, and then later edit my role to 'breeder', then I still have to refresh the page to see 'Import Traits'.

2021-02-19 21:02 UTC, dmeidlin commented
Ok, the active user role should be updated now when the active user role is edited in program management.

2021-02-23 18:25 UTC, DebWeigand approved these changes

2021-02-25 00:11 UTC, merged