BI-751 Create an interface to view an individual study and any observation data that’s been collected
Breeding-Insight/bi-web pull request #96
Opened 2021-06-28 01:27 UTC by dmeidlin

models and dao necessary for getting observationLevel value for an observation are in place. The changes needed in the ObservationService to pull the level value for each observation are left as a TODO.

2021-06-28 14:16 UTC, nickpalladino commented
Hey @dmeidlin could you merge 750 and rebase this PR to make it easier to review?

2021-07-09 00:24 UTC, timparsons requested changes
A few minor things, but looks good!

2021-07-09 00:24 UTC, timparsons commented on src/breeding-insight/model/Observation.ts
> +  traitId?: string;
I think this should be named `observationVariableId` or `variableId` to be in line with BrAPI

2021-07-09 00:24 UTC, timparsons commented on src/breeding-insight/model/Observation.ts
> +  traitName?: string;
I think this should be named `observationVariableName` or `variableName` to be in line with BrAPI

2021-07-09 00:24 UTC, timparsons commented on src/components/observations/ObservationsListTable.vue
> +    </NewDataForm>
I think this can be removed or commented out for this story

2021-07-09 00:24 UTC, timparsons commented on src/components/observations/ObservationsListTable.vue
> +      v-bind:archivable="$ability.can('archive', 'Observation')"
I think for this story, these can both be set to 'false' (or don't add that ability and it'll do the same thing 😄 )

2021-07-09 00:24 UTC, timparsons commented on src/components/observations/ObservationsListTable.vue
> +          You can add, edit, and delete observations from this panel.
I don't think this should display as of now

2021-07-12 15:09 UTC, nickpalladino reviewed
Tried running with some observation data from the discrete analyzer import and am getting an error. It looks like observations are being returned from the api call but there was some kind of issue displaying them
![Screenshot from 2021-07-12 11-05-37](https://user-images.githubusercontent.com/53413353/125311655-8faec480-e301-11eb-8328-357d6f1d0634.png)

2021-07-26 17:20 UTC, dmeidlin commented on src/breeding-insight/model/Observation.ts
> +  traitId?: string;
Yep, that makes sense: made the change.

2021-07-26 17:20 UTC, dmeidlin commented on src/breeding-insight/model/Observation.ts
> +  traitName?: string;
Thanks! Done.

2021-07-26 17:21 UTC, dmeidlin commented on src/components/observations/ObservationsListTable.vue
> +          You can add, edit, and delete observations from this panel.
done.

2021-07-26 17:22 UTC, dmeidlin commented on src/breeding-insight/dao/ObservationDAO.ts
> +        params: { full, studyDbId: studyId }
I added a check in the observation service for null values for season that should fix this.

2021-07-26 18:53 UTC, timparsons approved these changes

2021-07-26 20:58 UTC, nickpalladino approved these changes

2021-07-27 19:47 UTC, merged